--- 
knit: "bookdown::render_book"
title: "Fine-Scale Tracking of Ambient Temperature and Movement Reveals Shuttling Behavior of Elephants to Water"
author: "Maria Thaker, Pratik R. Gupte, Herbert HT Prins, Rob Slotow, and Abi T. Vanak"
date: "January 2019"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    fig_caption: yes
# bibliography: [refs.bib]
biblio-style: apalike
link-citations: yes
github-repo: pratikunterwegs/elephantTempKruger
description: "Source code for Thaker, Gupte et al. (2019)"
---

# About

This is the source code for the publication  
Thaker M, Gupte PR, Prins HHT, et al (2019) Fine-Scale Tracking of Ambient Temperature and Movement Reveals Shuttling Behavior of Elephants to Water. Front Ecol Evol 7:. [doi: 10.3389/fevo.2019.00004](https://www.frontiersin.org/articles/10.3389/fevo.2019.00004/full)

## Contact

**Corresponding author**  

Dr. Maria Thaker  
Centre for Ecological Sciences,  
Indian Institute of Science.
Email: m.thaker@iisc.ac.in

**Code maintainer**

Pratik R. Gupte  
Groningen Institute for Evolutionary Life Sciences,  
University of Groningen.  
Email: p.r.gupte@rug.nl


## Data access

The tracking dataset collected for use in this work is available from Movebank: https://doi.org/10.5441/001/1.403h24q5  
Other data used in this study are cited in the text.

## Data processing

The data processing for this project is described in the following sections. Navigate through them using the links in the sidebar.