---
  editor_options: 
    chunk_output_type: console
  chunk_output_type: console
---
  
# Load libs
  
```{r load_libs, message=FALSE, warning=FALSE}
#set env
library(plyr);library(dplyr);library(purrr);library(purrrlyr);library(data.table);library(lubridate);library(tidyr)

library(ggplot2)
```

```{r load_data}
#'source script
source("ele.code002.5dataloading.r")
```

# Split and arrange

```{r temp_change}
#'rate of tempchange as a relation to distance to water of points
ele02 = split(ele, ele$id)

#'order by timestamp
ele02 = ele02 %>% map(function(x) plyr::arrange(x, time))
```

```{r find_tempdiff}
library(zoo)
#'temp change
ele02 = ele02 %>% 
  map(function(x) mutate(x, tempdiff = c(NA, diff(x$temp, lag = 1)), waterdiff = c(diff(x$distw, lag = 1), NA)))
```


```{r bind_rows}
#'rbind the list to get the tempchange rates in a df
ele03 = bind_rows(ele02)
```


# Delta distance to water ~ temp

```{r delta.distw_temp}
png(file = "deltadistw_temp.png", width = 1600, height = 1600, res = 300)

ele03 %>% filter(abs(waterdiff) < 2e3) %>% 
  group_by(temp, season2) %>%
  summarise(mean.waterdiff = mean(waterdiff),
            sd.wd = sd(waterdiff), n.wd = length(waterdiff))  %>%
  mutate(wd.ci = qnorm(0.975)*sd.wd/sqrt(n.wd)) %>% 
  ggplot()+
  
  geom_hline(aes(yintercept = 0), col = "grey20", lty = 2, lwd = 0.3)+
  
    geom_point(aes(x = temp, y = mean.waterdiff, fill = season2, group = season2, shape = season2), position = position_dodge(width = 0.5), size = 3)+
  geom_linerange(aes(x = temp, ymin = mean.waterdiff-wd.ci, ymax = mean.waterdiff+wd.ci, col = season2), position = position_dodge(width = 0.5), lwd =0.5, lty = 2)+
    scale_fill_manual(values = c("royalblue1", "indianred1"),
                       labels=c("Cool", "Hot"))+
  scale_colour_manual(values = c("royalblue1", "indianred1"),
                       labels=c("Cool", "Hot"))+
  scale_shape_manual(values = c(21, 24),  labels=c("Cool", "Hot"))+
  
  geom_label(x=20, y = 50, label = "Away from water", col = "grey50", hjust = "inward", vjust = "inward")+
  geom_label(x=35, y = -40, label = "Towards water", col = "grey50", vjust = "inward")+
  
  theme_Publication()+
  theme(legend.position = c(0.85, 0.9),
        legend.background = element_rect(#fill="lightblue",
                                  size=0.5, linetype="solid"))+
  labs(list(x = "Temperature (°C)", y = "Δ Distance to water (m)", fill = "Season", shape = "Season", colour = "Season"))+ylim(-40,50)+xlim(15,40)

dev.off()
```

# Source weather data

```{r source_weather_data}
#'load weather data
source("ele.code003.5weatherdata.r")
```


# Consecutive time at water

```{r cons_watertime}
#'check if ele within 100m of water, assign numerical indicator
#'split into dfs and 
ele04 = ele03 %>% 
  mutate(m100 = distw <=  1e3, far = distw >= 10e3) %>% 
  dlply("id", identity) %>%
  map(function(x) mutate(x, watertime = sequence(rle(as.character(x$m100))$lengths),
                         awaytime = sequence(rle(as.character(x$far))$lengths))) %>% 
  bind_rows() %>% 
  mutate(watertime = ifelse(m100 == F, 0, watertime),
         awaytime = ifelse(far != F, awaytime, 0))

#'merge weather data with ele04
#ele04 = left_join(ele04, tempdata[,c("temp.a","time")], by = "time")

#ele04$season = as.factor(ele04$season)
```

# Plot temperature ~ time at water

```{r plot_watertime_temp}
#'plot tempdiff or var against time at water
png(file = "watertime_temp.png", width = 3200, height = 3200, res = 600)

ele04 %>% 
  filter(temp %in% 15:40) %>% 
  group_by(season2, temp) %>% 
  summarise(wt.mean = mean(watertime, na.rm = T), wt.sd = sd(watertime), wt.n = length(watertime),
            a.mean = mean(awaytime, na.rm = T), a.sd = sd(awaytime), a.n = length(awaytime)) %>% 
  mutate(wt.ci = qnorm(0.975)*wt.sd/sqrt(wt.n),
         a.ci = qnorm(0.975)*a.sd/sqrt(a.n)) %>% 
  
  ggplot()+
#'mean time at water
  geom_point(aes(x = temp, y = wt.mean/2, fill = season2, shape = season2), position = position_dodge(width = 0.5), size = 3)+
  
  #geom_point(aes(x = temp, y = a.mean/2, fill = season2, shape = season2), position = position_dodge(width = 0.5), size = 1)+

#'95% CI linerange
  geom_linerange(aes(x = temp, ymin = (wt.mean - wt.ci)/2, ymax = (wt.mean + wt.ci)/2, col = season2), lwd=0.5, lty = 2, position = position_dodge(width = 0.5))+
#'manual colour scale
  scale_colour_manual(values = c("royalblue1", "indianred1"),
                       labels=c("Cool dry", "Hot wet"))+
  scale_fill_manual(values = c("royalblue1", "indianred1"),
                       labels=c("Cool dry", "Hot wet"))+
  scale_shape_manual(values = c(21, 24),  labels=c("Cool dry", "Hot wet"))+
  
  
  theme_Publication()+
  theme(legend.position = c(0.2, 0.8), legend.justification = "center")+
 xlim(15,40) + 
 labs(list(x = "Temperature (°C)", y = "Cumulative time (hours) < 1 km to water", colour = "Season", fill = "Season", shape = "Season"))+
  scale_x_reverse()

dev.off()
```

```{r 3d_plot_tempdist}
p3d301 = plot_ly(a %>% filter(wd.mean > -1000), x = ~watertime, y = ~temp.mean, z = ~wd.mean, color = ~season2, colors = c("indianred1","royalblue")) %>% 
  add_markers() %>% 
  layout(scene = list(xaxis = list(title = "Fixes w/i 100m of water"),
                      yaxis = list(title = "Temperature (°C)"),
                      zaxis = list(title = "Δ distance to water")))
```

# Heating curves

```{r heating_curve}
png(filename = "deltatemp_hour.png", res = 300, width = 1600, height = 1600)

ele04 %>% group_by(season2, hour) %>% 
  summarise(mean.tempdiff = mean(tempdiff, na.rm = T), sd.tempdiff = sd(tempdiff, na.rm = T), n.tempdiff = length(tempdiff)) %>% 
  mutate(td.ci = qnorm(0.975)*sd.tempdiff/sqrt(n.tempdiff)) %>% 
  
  ggplot()+
  
  geom_hline(yintercept = 0, col = "grey50", lty = 2)+
   geom_linerange(aes(x = hour, ymin = mean.tempdiff-td.ci, ymax = mean.tempdiff+td.ci, col = season2), position = position_dodge(width = 0.5))+
  geom_point(aes(x = hour, y = mean.tempdiff, fill = season2, shape = season2), size = 3, position = position_dodge(width = 0.5))+
 
  
  scale_fill_manual(values = c("royalblue1", "indianred1"),labels = c("Cool dry", "Hot wet"))+
  scale_colour_manual(values = c("royalblue1", "indianred1"),labels = c("Cool dry", "Hot wet"))+
  scale_shape_manual(values = c(21,24), labels = c("Cool dry", "Hot wet"))+
    
    theme_Publication()+
  theme(legend.position = c(0.9,0.9))+
  labs(list(x = "Hour of day", y = "Δ temperature (°C)", fill = "Season", col = "Season", shape = "Season"))

dev.off()  
```

