---
editor_options: 
 chunk_output_type: console
---
  
# Load libs
  
```{r load_libs, message=FALSE, warning=FALSE}
#set env
library(plyr);library(dplyr);library(purrr);library(purrrlyr);library(data.table);library(lubridate);library(tidyr)

library(ggplot2)
```

```{r load_data}
#'source script
source("ele.code002.5dataloading.r")
```

```{r load_tempdata}
#'load the skukuza flux tower temp data
tempdata = read.csv("~/git/elephants/ele_data/skukuza_tower_temp.csv")

#'handle time and convert to posixct date time
tempdata$time = as.POSIXct(paste(tempdata$dd.mm.yyyy, tempdata$hh.mm, sep = " "), tz = "SAST", format = "%d/%m/%Y %H:%M")
```

# Ele to tower

```{r ele_to_tower}
#'get tower loc
towerloc = tempdata[1,c("long","lat")]

#'load spatial libs
library(sp); library(rgdal); library(proj4); library(geosphere)

#'find dist from ele to tower
ele$dist.tow = distVincentyEllipsoid(p1 = towerloc, p2 = ele[,c("long","lat")])

#'check ditr of dists
#hist(ele$dist.tow)
```

# Eles within 10km

```{r eles_near_tower}
#'keep only eles within 10km of the tower

quantile(ele$dist.tow, 0.01)

ele.tow = ele %>% filter(dist.tow < 1e4)
```

```{r match_temp_ele.tow}
#'match half hourly temp to the eles
#'first round the ele time to the half hour
ele.tow = ele.tow %>% mutate(roundtime = round_date(ele.tow$time, "30 minute"))

#'merge by time and round time
ele.tow = left_join(ele.tow, tempdata, by = c("roundtime" = "time"))
#'rename X.C
ele.tow = ele.tow %>% rename(temp.a = X.C)
tempdata = tempdata %>% rename(temp.a = X.C)

#'set all vals less than 0 to NA
ele.tow = ele.tow %>% mutate(temp.a = ifelse(temp.a < 0, NA, temp.a))
tempdata = tempdata %>% mutate(temp.a = ifelse(temp.a < 0, NA, temp.a))
```

# Plot temp_a and temp

```{r body_amb_temp_prep}
#'plot elephant body and ambient temp
ele.tow02 = ele.tow %>% filter (dist.tow<=1e4) %>% group_by(hour = hour(time)) %>% 
  summarise(meantemp = mean(temp), n = length(temp), sd = sd(temp)) %>% 
  mutate(t.ci = qnorm(0.975)*sd/sqrt(n))

towtemp = tempdata %>% group_by(hour = hour(time)) %>% 
  summarise(meantempa = mean(temp.a, na.rm= T), n.ta = length(temp.a), sd.ta = sd(temp.a, na.rm = T)) %>% 
  mutate(ta.ci = qnorm(0.975)*sd.ta/sqrt(n.ta))
```

# Plot hourly temp

```{r plot_tb_ta}
#'plot starts here
#png(file = "fig01.1collar_tower_temp.png", width = 1600, height = 1600, res = 300)

  ggplot()+
    geom_linerange(data = ele.tow02, aes(x = hour, ymin = meantemp-t.ci, ymax = meantemp+t.ci, col = "seagreen"), position = position_dodge(width = 1.5), show.legend = F, lty = 1, lwd = 0.4)+
    
  geom_point(data = ele.tow02, aes(x = hour, y = meantemp, fill = "seagreen", shape = "b"), position = position_dodge(width = 1.5), size = 3, show.legend = F)+
  
  geom_point(data = towtemp, aes(x = hour, y = meantempa, fill = "sandybrown", shape = "a"), size = 3)+

  geom_linerange(data = towtemp, aes(x = hour, ymin = meantempa-ta.ci, ymax = meantempa+ta.ci, colour = "sandybrown"))+
  
  scale_fill_manual(values = c("sandybrown","seagreen"), labels = c("Ambient", "Elephant"))+
  scale_colour_manual(values = c("sandybrown","seagreen"), labels = c("Ambient", "Elephant"))+
  scale_shape_manual(values = c(21, 24), labels = c("Ambient", "Elephant"))+
  theme_Publication()+
  theme(legend.position = c(0.9, 0.9))+
  labs(list(x = "Hour of day", y = "Temperature (°C)", colour = NULL, fill = NULL, shape = NULL))

dev.off()
```

# Correlogram for hourly mean temps from eles ~ tower

```{r temp_matrix}
#'correlation between columns of x and y
#'set data and column names for eledata dry season

ele.tow03.dry = ele.tow %>% filter(dist.tow <=1e4, season2 == "dry") %>% mutate(hour = as.factor(hour(time))) %>% select(hour, temp) %>%  group_by(hour) %>% mutate(ind = row_number()) %>% 
spread(hour, temp, fill = NA) %>% select(-ind)

#'set data for the wet season
ele.tow03.wet = ele.tow %>% filter(dist.tow <=1e4, season2 == "wet") %>% mutate(hour = as.factor(hour(time))) %>% select(hour, temp) %>%  group_by(hour) %>% mutate(ind = row_number()) %>% 
spread(hour, temp, fill = NA) %>% select(-ind)

#'set colnames
colnames(ele.tow03.dry) = c(paste("ele", 1:24, sep="_"))
colnames(ele.tow03.wet) = c(paste("ele", 1:24, sep="_"))

#'set columns for the tower data for the dry season
towtemp03.dry = ele.tow %>% filter(dist.tow<=1e4, season2 == "dry") %>% mutate(hour = as.factor(hour(time))) %>% select(hour, temp.a) %>%  group_by(hour) %>% mutate(ind = row_number()) %>% 
spread(hour, temp.a, fill = NA) %>% select(-ind)

#'for the wet season
towtemp03.wet = ele.tow %>% filter(dist.tow<=1e4, season2 == "wet") %>% mutate(hour = as.factor(hour(time))) %>% select(hour, temp.a) %>%  group_by(hour) %>% mutate(ind = row_number()) %>% 
spread(hour, temp.a, fill = NA) %>% select(-ind)

#'set colnames
colnames(towtemp03.dry) = c(paste("amb", 1:24, sep="_"))
colnames(towtemp03.wet) = c(paste("amb", 1:24, sep="_"))
```

```{r corrs}
#'correlation between the columns of each df for the dry season
tempcor.dry = cor(towtemp03.dry, ele.tow03.dry, use = "na.or.complete")
p.mat.dry = cor.mtest(tempcor.dry)
#'for the wet season
tempcor.wet = cor(towtemp03.wet, ele.tow03.wet, use = "na.or.complete")
p.mat.wet = cor.mtest(tempcor.wet)
```

```{r custom_pval_matrix_func}
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
```


```{r plot_correlogram_dry}
#'corrplot for the dry season
library(corrplot);library(RColorBrewer)
col<- colorRampPalette(c("red", "white", "blue"))(20)

png(file = "temp_corr_dry.png", width = 2000, height = 2000, res = 600)
corrplot(tempcor.dry, method = "shade", type = "lower", col=brewer.pal(n=8, name="RdYlBu"), tl.col="black", tl.srt=45,
         p.mat = p.mat, sig.level = 0.05, insig = "blank",
         tl.cex = 0.5)
dev.off()
```

```{r plot_correlogram_wet}
#'plot a correlogram for the wet season
png(file = "temp_corr_wet.png", width = 2000, height = 2000, res = 600)
corrplot(tempcor.wet, method = "shade", type = "lower", col=brewer.pal(n=8, name="RdYlBu"), tl.col="black", tl.srt=45,
         p.mat = p.mat.wet, sig.level = 0.05, insig = "blank",
         tl.cex = 0.5)
dev.off()
```


```{r corrplot_ggplot}
library(ggcorrplot)
ggcorrplot(tempcor.dry, method = "square", type = "lower")

```

# Scatterplot

```{r}
png(filename = "fig1.02temp_correlation.png", res = 300, width = 1600, height = 1600)

ele.tow %>% filter(dist.tow <= 1e4) %>% 
  group_by(season2, temp.a = round(temp.a)) %>%
  summarise(mt = mean(temp, na.rm = T), sd.mt = sd(temp, na.rm = T), n.mt = length(temp)) %>% 
  mutate(mt.ci = qnorm(0.975)*sd.mt/sqrt(n.mt)) %>% 
  
  ggplot()+
  geom_smooth(aes(x = temp.a, y = mt, col = season2, group = season2), method = "glm", show_guide = F)+
  
  geom_point(aes(x = temp.a, y = mt, fill = season2, shape = season2), size = 3, position = position_dodge(width = 0.5))+
  
  geom_linerange(aes(x = temp.a, ymin = mt-mt.ci, ymax = mt+mt.ci, col = season2), lty = 1, lwd = 0.4, position = position_dodge(width = 0.5))+
  
  scale_fill_manual(values = c("royalblue1", "indianred1"), labels = c("Cool", "Hot"))+
  scale_shape_manual(values = c(21, 24),  labels=c("Cool", "Hot"))+
  scale_colour_manual(values = c("royalblue1", "indianred1"),
                       labels=c("Cool", "Hot"))+
  theme_Publication()+
  theme(legend.key = element_rect(fill = "white"), legend.position = c(0.2, 0.9))+
  labs(list(x = "Ambient temperature (°C)", y = "Elephant temperature (°C)", colour = "Season", fill = "Season", shape = "Season"))

dev.off()
```

