---
editor_options:
  chunk_output_type: console
---

# Load libs

```{r load_libs, message=FALSE, warning=FALSE}
#set env
library(plyr);library(dplyr);library(purrr);library(purrrlyr);library(data.table);library(lubridate)

library(ggplot2)
```

# Load data

```{r import_data}
#read in data from saved csv files

ele.dry = read.csv("~/git/elephants/ele_data/ele.dry.csv", header = T)
ele.wet = read.csv("~/git/elephants/ele_data/ele.wet.csv", header = T)
```

```{r reduce_data}
#keep basic columns
#'note: south africa is in the SAST time zone, UTC+2

#'subset and rename for easier typing
ele.dry02 = ele.dry %>% select(id = ID, ref = REF, long = LONGITUDE, lat = LATITUDE, temp = TEMP, season = SEASON, xutm = XUTM, yutm = YUTM, time = Date_time, landscape = landsca, land.val = VALUE, density = DENSITY, woody.density, veg.class = VEG_CLASS, gertcode = Gertcode, v = STEPLENGTH, angle = TURNANGLE, heading = BEARING, distw = dist_water)

ele.wet02 = ele.wet %>% select(id = ID, ref = REF, long = LONGITUDE, lat = LATITUDE, temp = TEMP, season = SEASON, xutm = XUTM, yutm = YUTM, time = Date_time, landscape = landsca, land.val = VALUE, woody.density, density = DENSITY, veg.class = VEG_CLASS, gertcode = GertLANDSCAPE, v = STEPLENGTH, angle = TURNANGLE, heading = BEARING, distw = dist_water)

```

```{r map_data}
#'map coords by id
library(ggplot2)

#'map dry season
ele.dry02 %>% select(long, lat, id, season) %>%
  ggplot()+
  geom_path(aes(x = long, y = lat, group = id, col = id))+
  theme_minimal()

#'map wet season
ele.wet02 %>% select(long, lat, id, season) %>%
  ggplot()+
  geom_path(aes(x = long, y = lat, group = id, col = id))+
  theme_minimal()
```

## Assign and merge

```{r merge_data}
#merge datasets after assigning seasons
ele.dry02$season2 = "dry"; ele.wet02$season2 = "wet"

#'rbind the data
ele = rbind(ele.dry02, ele.wet02)

#'change time to posixct via char
ele$time = as.POSIXct(as.character(ele$time), tz = "SAST", format = "%d-%m-%Y %H:%M")
```

## Make spatial, write shapefile

```{r make_spatial}
#'make the cleaned dataset spatial
library(sp)

#'add year, month and hour of day, remove the posixct class time
ele.sp = ele %>% mutate(year = year(time), month = month(time),
                        hour = hour(time)) %>% select(-time)
coordinates(ele.sp) = ~long+lat
```

```{r write_shapefile}
#'write to shapefile
library(maptools)

writePointsShape("elephants_clean_all", x = ele.sp)
```

# Temporal sample distribution

```{r sample_time_heatmaps}

#'heatmap ele by year and season, midpoint at 5k
#'count ele positions and plot

source("ggplot.opts.r")
load("eledata.rdata")

cairo_pdf(filename = "ele_figA2.pdf", height = 4, width = 8)

viridis = viridis(3)

ele2 %>% mutate(season = ifelse(season2 == "wet", "Hot","Cool")) %>% group_by(year_season = paste(year(time), season, sep = " ")) %>% count(id) %>%
  ggplot()+
  geom_tile(aes(x = id, y = year_season, fill = n))+
  theme_minimal()+
  scale_fill_gradient2(low = viridis[1], mid = viridis[2],
                       high = viridis[3], midpoint = 5e3)+
  theme(axis.text.x = element_text(angle = 20, hjust = 1),legend.position = "top")+
  labs(list(x = "Elephant",y = "Year & season", fill = "Fixes"))

dev.off()
```

```{r fix_heatmap_year_month_export}
png(file = "eles_year_month_data.png", width = 3200, height = 1600, res = 600)
#'plot by year and month
ele %>% group_by(year_month = paste(year(time), ifelse(month(time)<10, paste(0, month(time), sep = ""), month(time)), sep = "_")) %>% count(id) %>%
  ggplot()+
  geom_tile(aes(x = id, y = year_month, fill = n))+
  theme_minimal()+
  scale_fill_gradient2(low = "#fc8d59", mid = "#ffffbf",
                       high = "#1a9850", midpoint = 750)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6),
        axis.text = element_text(family = "monospace"))+
  labs(list(fill = "GPS fixes", x = "Individual", y = "Time (year_month)"))+
  coord_flip()

dev.off()
```

```{r ggplot_axis_ops}
mono = theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(family = "monospace"))
```


# Summary stats

```{r summary_stats}
#'count points per ele and plot
ele %>%
  ggplot()+
  geom_bar(aes(x=id), fill = "skyblue")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(family = "monospace"))+
  labs(list(x = "Ele", y = "Fixes"))+
  facet_grid(season2~year(time))
```

```{r distr_vars}
#'plots
ele %>%
  ggplot()+
  geom_boxplot(aes(x = as.factor(season2), y = distw, fill = as.factor(season2)))+
 # facet_wrap(~season)+
  theme_minimal()+
  labs(list(x = "Distance to water (m)", y = "Count"))
```

# Recreate plots

```{r explore_seasons}
#'make season a factor
ele$season = as.factor(ele$season)

ele %>%
  ggplot()+
  geom_boxplot(aes(x = season, y = distw, fill = season))+
  theme_minimal()
```

# Plot 2: Eles are closer to water in the afternoon

```{r distw_time_season}
#'plot the distanc to the nearest water source against hour of day

png(file = "distw_time.png", width = 3200, height = 2000, res = 600)
#'plot
ele %>% group_by(hour = hour(time), season2) %>% summarise(distw.mean = mean(distw), n = length(distw), distw.sd = sd(distw)) %>%
  mutate(distw.ci = qnorm(0.975)*distw.sd/sqrt(n)) %>%

  ggplot()+
  geom_point(aes(x = hour, y = distw.mean/1e3, col = season2), size = 2)+
  geom_linerange(aes(x = hour, ymin = (distw.mean-distw.ci)/1e3, ymax = (distw.mean+distw.ci)/1e3, col = season2))+
  scale_colour_manual(values = c("royalblue", "indianred1"),
                      labels = c("Cool","Hot"))+
  theme_bw()+
  theme(legend.position = c(0.9, 0.85),
        legend.background = element_rect(#fill="lightblue",
                                  size=0.5, linetype="solid"),
        axis.title = element_text(size = 10))+

  labs(list(x = "Hour of day", y = "Distance to nearest water source (km)",
            col = "Season"))

dev.off()
```

```{r temp_distr}
#'plot ele temp distributions

ele %>%
  ggplot()+
  geom_histogram(aes(x = temp, fill = season))+
  theme_minimal()+
  labs(list(x = "Temperature (°C)", y = "Count", fill = "Season"))
```

# Plot 3: Eles cool down near water

```{r temp_distw_season}
#'plot mean temp with se against distance to water for every 100m interval per season

png(file = "temp_distw.png", width = 3200, height = 2000, res = 600)

ele %>% group_by(season2, distw_round = round_any(distw, 100)/1e3) %>%
  summarise(t.mean = mean(temp), n = length(temp), sd = sd(temp)) %>%
  mutate(t.ci = qnorm(0.975)*sd/sqrt(n)) %>%

  ggplot()+
  geom_point(aes(x = distw_round, y = t.mean, col = season2), size = 2)+
  geom_linerange(aes(x = distw_round, ymin = t.mean-t.ci, ymax = t.mean+t.ci, col = season2))+
  scale_colour_manual(values = c("royalblue", "indianred1"),
                       labels=c("Cool", "Hot"))+
  theme_bw()+
  theme(legend.position = c(0.9, 0.85),
        legend.background = element_rect(#fill="lightblue",
                                  size=0.5, linetype="solid"))+
  xlim(0,5) + ylim(26.5, 29)+
  labs(list(x = "Distance to nearest water-source (km)", y = "Temperature (°C)",
            col = "Season"))

dev.off()
```

# Plot 4: Eles go faster at higher temps

```{r speed_temp}
#'plot mean steplength against temp per season
png(file = "speed_temp.png", width = 3200, height = 2000, res = 600)


ele %>% filter(v <=500, round(temp) %in% 15:40) %>% mutate(tempclass = round_any(temp, 1)) %>% group_by(season2, tempclass) %>%
  summarise(v.mean = mean(v), v.sd = sd(v), n.v = length(v)) %>%
  mutate(v.ci = qnorm(0.975)*v.sd/sqrt(n.v)) %>%

  ggplot()+
  geom_point(aes(x = tempclass, y = v.mean, col = season2), size = 2)+
  geom_linerange(aes(x = tempclass, ymin = v.mean-v.ci, ymax = v.mean+v.ci, col = season2))+
  scale_colour_manual(values = c("royalblue", "indianred1"),
                      labels = c("Cool", "Hot"))+
  theme_bw()+
  theme(legend.position = c(0.1, 0.85),
        legend.background = element_rect(#fill="lightblue",
                                  size=0.5, linetype="solid"))+
  labs(list(x = "Temperature (°C)", y = "Speed (m/30 minutes)",
            col = "Season"))

dev.off()
```

# Plot 5: Eles travel faster closer to water

```{r speed_distw}
#'plot mean speed against distance to water per season
png(file = "speed_distw.png", width = 3200, height = 2000, res = 600)

ele %>% group_by(season2, distw_round = round_any(distw, 100)/1e3) %>%
  summarise(v.mean = mean(v), v.n = length(v), sd = sd(v)) %>%
  mutate(v.ci = qnorm(0.975)*sd/sqrt(v.n)) %>%

  ggplot()+
  geom_point(aes(x = distw_round, y = v.mean, col = season2), size = 2)+
  geom_linerange(aes(x = distw_round, ymin = v.mean-v.ci, ymax = v.mean+v.ci, col = season2))+
  scale_colour_manual(values = c("royalblue", "indianred1"),
                                 labels = c("Cool","Hot"))+
  theme_bw()+
  theme(legend.position = c(0.8, 0.85),
        legend.background = element_rect(#fill="lightblue",
                                  size=0.5, linetype="solid"))+
  xlim(0, 5) + ylim(160, 240)+
  labs(list(x = "Distance to nearest water-source (km)", y = "Steplength (m/30 minutes)", col = "Season"))

dev.off()
```
