---
  editor_options:
  chunk_output_type: console
---

# Load libs

```{r load_libs, message=FALSE, warning=FALSE}
#set env
library(plyr);library(dplyr);library(purrr);library(purrrlyr);library(data.table);library(lubridate)

library(ggplot2)
```

```{r load_ele_amb_temp}
#'read in ambient temp data
ele.ambtemp = read.csv("~/git/elephants/ele_data/ele_ambient_temp.csv")
```

```{r fix_data}
#'fix df as with prev ones
ele.ambtemp = ele.ambtemp %>% select(distw = Dist_openw, id = ID, long = LONGITUDE, lat = LATITUDE, temp = TEMP, season = SEASON, xutm = XUTM, yutm = YUTM, time = Date_time, speed = STEPLENGTH, angle = TURNANGLE, temp_a)

#'fix time
ele.ambtemp$time = as.POSIXct(as.character(ele.ambtemp$time), tz = "SAST", format = "%d/%m/%y %H:%M")
```


```{r data_distr_time}

#'which eles are here and over which months?
tower.eles = ele.ambtemp %>% group_by(year_month = paste(year(time), ifelse(month(time)<10, paste(0, month(time), sep = ""), month(time)), sep = "_")) %>% count(id) %>%
  ggplot()+
  geom_tile(aes(x = id, y = year_month, fill = n), col = 1, lwd = 0.2)+
  theme_pub()+
  scale_fill_gradientn(colours  = brewer.pal(9, "Greys"))+
  theme(axis.text.x = element_text(angle = 20, hjust = 1), legend.position = "top", axis.line = element_blank())+
  labs(list(fill = "Fixes", x = "Elephant", y = "Time (year_month)", title = "(b)"))+
  coord_flip()

```

```{r}
pdf(file = "data.densities.pdf", height = 6, width = 5)

grid.arrange(data.density, tower.eles, ncol=1)

dev.off()

```

