---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
#'load libs
source("libs.R");library(sf);source("ggplot.pub.r")

#'load rivers and waterholes and crop to study area
rivers <- st_read("spatial/river_crop/kruger_rivers_cropped.shp")
wh <- st_read("~/git/elephants/ele_data/gis_etc/Kruger Updated GIS Layers/waterpoints_zambatis_2011.shp")

ext = st_read("spatial/ele_ext.shp")

#'sample in the ext
#samples <- st_sample(ext, 2e5, "random")

wh <- wh %>% filter(CURRENT=="Open") %>% 
  st_crop(ext)
```

```{r}
#'get water distribution in dry and wet season; is constant for waterholes
distwh <- apply(st_distance(samples, wh),1, min)

#'remove seasonal rivers from the dry season
river_seasons <- list(rivers %>% filter(is.na(seasonal)), rivers)

#'get distances
dist_dry <- apply(st_distance(samples, river_seasons[[1]]),1, min)
save(dist_dry, file = "distr_rand_dry.rdata");rm(dist_dry)

dist_wet <- apply(st_distance(samples, river_seasons[[2]]),1, min)
save(dist_wet, file = "distr_rand_wet.rdata");rm(dist_wet)
#distr_seasonal <- map(river_seasons, function(x){
 # apply(st_distance(samples, x), 1, min)
#})
```

```{r}
#'load dist to water
load("distr_rand_dry.rdata");load("distr_rand_wet.rdata");load("distwh.rdata")
#'add distances to samples
rand_mindw <- data_frame(distwh, distr_dry = dist_dry, distr_wet = dist_wet) %>% 
  gather(season, distr, -distwh) %>% 
  mutate(season = case_when(season == "distr_dry" ~ "dry", T ~ "wet"),
         mindw = case_when(distwh < distr ~ distwh, T ~ distr))
```

```{r}
load("eledata.rdata")
ele <- as.data.frame(ele) #%>% sample_n(1e4)

data <- bind_rows(rand_mindw %>% mutate(data = "rand") %>% select(data,season, mindw),
                  ele %>% mutate(data = "ele", season = season2) %>%  select(data,season,mindw))
#'plot distribution
fig_water_distr <- 
  ggplot()+
  geom_rangeframe(data = data_frame(x=c(0,5), y=c(0,.1)), aes(x,y))+
  
  stat_density(data = rand_mindw, aes(x = mindw/1e3, y = ..density../10, col = season), geom = "line", position = "identity", lty = 2, size = 0.4)+
  stat_density(data = ele, aes(x = mindw/1e3, y = ..density../10, col = season2), geom = "line", position = "identity", lty = 1, size = 0.4)+
    
  #geom_vline(xintercept = mean(data$mindw))+
  scale_color_brewer(palette = "Set1")+
  theme_pub()+
  
  scale_x_continuous(breaks = c(0,5))+
  scale_y_continuous(breaks = c(0,0.1))+
  coord_cartesian(xlim=c(0,5))+
  labs(list(x = "Distance to water (km)",y = "% Positions"))

ggsave(filename = "figs/fig_water_distr.png", fig_water_distr, device = png(),width = half, height = half);dev.off()
```

```{r}
#'KS test for points
ks.dry <- ks.test(x = ele %>% filter(season2 == "dry") %>% .$mindw, y = rand_mindw %>% filter(season == "dry") %>% .$mindw)

ks.wet <- ks.test(x = ele %>% filter(season2 == "wet") %>% .$mindw, y = rand_mindw %>% filter(season == "wet") %>% .$mindw)
```

```{r}
#'save data
save(ks.dry, ks.wet, rand_mindw, file = "water_distribution.rdata")
```

