# Load waterholes data

```{r load waterholes}
#'load and save as csv or spdf
library(sf)
wh = st_read("~/git/elephants/ele_data/gis_etc/Kruger Updated GIS Layers/waterpoints_zambatis_2011.shp")

#plot(wh, col = wh$CURRENT)

wh = wh %>% filter(CURRENT=="Open")

st_crs(wh)$proj4string

wh.spat = as(wh, "Spatial")

#wh.deg = st_transform(wh, 4326)
#wh.deg = as(wh.deg, "Spatial")
```

# Load rivers

```{r load rivers}
#load rivers

rivers = st_read("~/git/elephants/ele_data/gis_etc/Kruger Updated GIS Layers/rivers_main.shp")

st_crs(rivers)

rivers.deg = st_transform(rivers, 4326)
rivers.deg = as(rivers.deg, "Spatial")
```


```{r make spatial}
coordinates(ele)=~xutm+yutm
raster::crs(ele) = st_crs(wh)$proj4string
```

# Get distances

## Waterholes

```{r distw waterholes}
#'library(geosphere)
dwh = spDists(ele, as(wh, "Spatial"))

dwh = apply(dwh, 1, min)
```

## Rivers

```{r dist rivers}
#'sample along river
driv = gDistance(as(rivers, "Spatial"), ele, byid = T)

driv = apply(driv, 1, min)
```

## Combine

```{r dist water}
ele$distr_old = ele$distr
ele$distw_old = ele$distw

ele$distr = driv
ele$distwh = dwh

#'which water source is closest?
ele$which.water = apply(as.data.frame(ele)[,c("distwh","distr")],1, which.min)

ele$which.water = as.factor(ele$which.water)
levels(ele$which.water) = c("wh","river")

#'how far is the nearest water?
ele$mindw =  apply(as.data.frame(ele)[,c("distwh","distr")],1, min)
```