---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r reglibs}
#'load libs
source("libs.R")

```

```{r spatial libs}
library(sp);library(maptools);library(rgeos);library(geosphere);library(sf)
```

# Load waterholes data

```{r load waterholes}
#'load and save as csv or spdf

wh = st_read("~/git/elephants/ele_data/gis_etc/Kruger Updated GIS Layers/waterpoints_zambatis_2011.shp")

#plot(wh, col = wh$CURRENT)

wh = wh %>% filter(CURRENT=="Open")

st_crs(wh)$proj4string

wh.spat = as(wh, "Spatial")

#wh.deg = st_transform(wh, 4326)
#wh.deg = as(wh.deg, "Spatial")
```

# Load rivers

```{r load rivers}
#load rivers

rivers = st_read("~/git/elephants/ele_data/gis_etc/Kruger Updated GIS Layers/rivers_main.shp")

st_crs(rivers)

rivers.deg = st_transform(rivers, 4326)
rivers.deg = as(rivers.deg, "Spatial")
```

# Load eles and make spatial

```{r load eles}
#'load eles
detach("package:raster", unload=TRUE)
source("ele.code002.5dataloading.r")
```

```{r make spatial}
coordinates(ele)=~xutm+yutm
raster::crs(ele) = st_crs(wh)$proj4string
```

# Get distances

## Waterholes

```{r distw waterholes}
#'library(geosphere)
dwh = spDists(ele, as(wh, "Spatial"))

dwh = apply(dwh, 1, min)
```

## Rivers

```{r dist rivers}
#'sample along river
driv = gDistance(as(rivers, "Spatial"), ele, byid = T)

driv = apply(driv, 1, min)
```

## Combine

```{r dist water}
ele$distr_old = ele$distr
ele$distw_old = ele$distw

ele$distr = driv
ele$distwh = dwh

#'which water source is closest?
ele$which.water = apply(as.data.frame(ele)[,c("distwh","distr")],1, which.min)

ele$which.water = as.factor(ele$which.water)
levels(ele$which.water) = c("wh","river")

#'how far is the nearest water?
ele$mindw =  apply(as.data.frame(ele)[,c("distwh","distr")],1, min)
```

```{r}
#'make df

ele2 =  data.frame(ele)
```


# Move data

```{r move_obj}
#'make move, arrange by id, and time
ele2 = ele2 %>% plyr::arrange(id, time)

library(move)

ele.move = move(x = ele2$xutm, y = ele2$yutm, 
                  time = ele2$time, animal = ele2$id,
                  proj = CRS("+proj=utm +zone=36 +south +datum=WGS84 +units=m +no_defs"), data = ele2)
```

```{r get_stats}
#'get distance, timediff, speed
ele.move = split(ele.move)

for(i in 1:length(ele.move)){
  ele.move[[i]]$lag = c(NA, timeLag(ele.move[[i]]))
  ele.move[[i]]$distance = c(NA, distance(ele.move[[i]]))
  ele.move[[i]]$calc.speed = c(NA,speed(ele.move[[i]]))
}

#'make a list of dfs and bind
ele2 = lapply(ele.move, as.data.frame)
ele2 = bind_rows(ele2)
```

## Filter moving animals

```{r filter moving animals}
#'moving animals, ie, distance covered over 100m, bad timelags, less than 10mins or over 60mins
ele2 = ele2 %>% filter(lag %in% 20:60)
#ele2 = ele2 %>% filter(distance > 100)

#ele2$id = ele2$from.idData.rep.1..n.locs.from.....
```

```{r}
#'round temp to 2
ele2 = ele2 %>%
  dlply("id") %>% 
  map(function(x) mutate(x, temp = round_any(temp,2)))

ele2 = ele2 %>%  
  map(function(x) {
    mutate(x, tempdiff = c(NA, diff(x$temp, lag = 1)), waterdiff = c(diff(x$mindw, lag = 1), NA), meanspeed = rollapply(x$v, 3, mean, fill = NA), moving = meanspeed>100) %>% mutate(towater = as.factor(ifelse(waterdiff < 0, "to", "away")))
  }) %>% bind_rows()

ele2 = ele2 %>% dplyr::select(-c(distw, coords.x1, coords.x2, optional.1, optional))

ele2 = ele2 %>%
  dlply("id") %>% map(function(x) mutate(x, meantdiff = rollapply(x$tempdiff, 3, mean, fill = NA))) %>% bind_rows()

ele2 = ele2 %>% filter(v > 0, temp %in% 15:40)

ele2$distwold = apply(ele2[,c("distwh","distr")], 1, min)
```


# Export to csv

```{r}
#ele2 = as.data.frame(ele)
#'export data
write.csv(ele2, file = "eledata.csv", row.names = F)

save(ele2, file = "eledata.rdata")
```

# Map data

## Get map data for woodland etc

```{r get waterdiff and tdiffdata}
#ele02 = ele %>% dlply("id") %>%
  map(function(x) plyr::arrange(x, time) %>% mutate(tempdiff = c(NA, diff(temp, lag = 1)), waterdiff = c(diff(mindw, lag = 1), NA))) %>% bind_rows()
```


```{r get_data_maps}
#'set resolution
res = 500

#'pool across 500m degrees
ele.map = ele02 %>% group_by(xutm = round_any(xutm, res), yutm = round_any(yutm, res)) %>% summarise(meantemp = mean(temp), meanwood = mean(woody.density), minwh = min(distwh2), minriver = min(distr2), meanwh = mean(distwh2), meanriver = mean(distr2), meandistw = mean(mindw), propriver = sum(which.water == "river")/length(which.water), propheading = sum(waterdiff<0)*100/length(waterdiff), meantempchange = mean(tempdiff, na.rm = T), meanheadingchange = mean(waterdiff, na.rm = T))
```

# Old ele maps

```{r old_distw_map}
res = 500

ele.map.old = ele %>% group_by(xutm = round_any(xutm, res), yutm = round_any(yutm, res)) %>% summarise(meantemp = mean(temp), meanwood = mean(woody.density), meanwh = mean(distw), meanriver = mean(distr), meandistw = mean(mindw))

write.csv(ele.map.old, file = "elemapold.csv")
```


# Export for map

```{r}
write.csv(ele.map, file = "ele_map2.csv")
```

# Export supplementary material

Histogram of distwh, distr, mindw, woody-density

```{r supplement figures}
g2 = theme(axis.text.y = element_text(size = 6))

blues = rev(colorRampPalette(brewer.pal(9,"YlGnBu"))(20))
greens = (colorRampPalette(brewer.pal(9,"YlGn"))(20))
figa1.1 =
  ggplot(ele2)+
  geom_histogram(aes(x = mindw/1e3), fill =blues, bins = 20)+
  theme_bw()+g1+
  labs(list(x = "Distance to nearest water source (km)",y = NULL))+xlim(NA,11.45)+scale_x_continuous(breaks = seq(0,10,2))+g2

figa1.2 = 
 ggplot(ele2)+
  geom_histogram(aes(x = distr/1e3), fill = blues, bins = 20)+
  theme_bw()+g1+
  labs(list(x = "Nearest river (km)",y = NULL))+theme(axis.title = element_text(size = 8))+g2#+xlim(NA,10)

figa1.3 = 
 ggplot(ele2)+
  geom_histogram(aes(x = distwh/1e3), fill = blues, bins = 20)+
  theme_bw()+g1+
  labs(list(x = "Nearest waterhole (km)",y = NULL))+theme(axis.title = element_text(size = 8))+g2#+xlim(NA,10)

figa2 =
  ggplot(ele2)+
   geom_histogram(aes(x = woody.density), fill = greens, bins = 20)+
  theme_bw()+g1+
  labs(list(x = "Woody density",y = NULL))+g2
```

```{r export figA1}
cairo_pdf(filename = "figA1.pdf", width = 8, height = 4)
library(gridExtra)
grid.arrange(figa1.1, figa1.2, figa1.3, figa2, layout_matrix = rbind(c(1,1,4,4),c(2,3,4,4)))
dev.off()
```

