---
editor_options: 
 chunk_output_type: console
---

# Temperature, speed, distance to water
Plotting and models for figs 3a, b, c.

3a. Temp ~ distw
3b. Speed ~ distw
3c. Speed ~ temp

Elephant speed at the landscape scale is mediated by temperature.

# Load libs
  
```{r load_libs, message=FALSE, warning=FALSE}
#set env
library(plyr);library(dplyr);library(purrr);library(purrrlyr);library(data.table);library(lubridate);library(tidyr)

library(ggplot2)
```

```{r load_data}
#'source script
source("ele.code002.5dataloading.r")
source("ggplot.opts.r")
```

# Model: Elephants cool down near water

```{r mod_temp_distw}
#'use a lmm here
library(lme4)

#'rescale distw
ele$distw = ele$distw/1e3
#'run mod
mod.temp.distw = bam(temp ~ s(distw, by = season2, bs = "cr")+
                       s(hour, bs = "cc") + woody.density+
                       s(id, bs = "re")+s(gertcode, bs = "re")+s(season2, bs="re"), data = ele, na.action = na.omit)

#'summary
#summary(mod.temp.distw)
#car::Anova(mod.temp.distw)

#'plot
#plot(mod.temp.distw)
```

# Prep data

```{r prep_data}
ele.temp.distw = ele %>%
  mutate(pred = predict(mod.temp.distw, newdata = ., scale = "response")) %>% group_by(season2, distw_round = round_any(distw, 0.15)) %>%
  summarise(t.mean = mean(temp), n = length(temp), sd = sd(temp), pred.mean = mean(pred, na.rm = T), pred.n = length(pred), pred.sd = sd(pred, na.rm = T)) %>%
  mutate(t.ci = qnorm(0.975)*sd/sqrt(n), pred.ci = qnorm(0.975)*pred.sd/sqrt(pred.n))
```

# Fig 3a. Temp ~ distw

```{r plot.mod.temp.distw}
#'plot and save

fig3a = 
ele.temp.distw %>% 
  ggplot()+
#  geom_ribbon(aes(x = distw_round, ymin = pred.mean-pred.ci, ymax = pred.mean+pred.ci, group = season2), fill = "grey", alpha = 0.5)+
#  geom_line(aes(x = distw_round, y = pred.mean, col = season2), lty = 1, lwd = 0.4)+
  geom_pointrange(aes(x = distw_round, y = t.mean, ymin = t.mean-t.ci, ymax = t.mean+t.ci, col = season2, shape = season2), fatten = 10, stroke = 0.7, fill = "white", position = position_dodge(width = 0.5),lwd = 0.2, lty = 1)+
  scale_colour_manual(values = c(cola,colb))+
  scale_shape_manual(values = c(21,24))+
  theme_bw()+g1+
  xlim(0,5)+ylim(26.5,29)+
  labs(list(x = "Distance to water source (km)", y = "Temperature (°C)",
            col = "Season"))
 # facet_wrap(~season2, ncol = 1, strip.position="right")+theme(strip.text=element_blank(), strip.background=element_blank(), panel.spacing.y=unit)

dev.off()
```

----

# Speed

# Reload data

```{r load_data}
#'source script
source("ele.code002.5dataloading.r")
```

```{r mod.speed}
#'glmm
ele$v = round(ele$v)
ele2 = ele %>% filter(v>0, round(temp) %in% 15:40) %>%
  dlply("id") %>% map(function(x) mutate(x, tempdiff = c(NA, diff(x$temp, lag = 1)), waterdiff = c(diff(x$distw, lag = 1), NA)) %>% mutate(towater = as.factor(ifelse(waterdiff < 0, "to", "away")))) %>% bind_rows()

#'prelim plot
#ele2 %>% filter(v <200) %>% ggplot()+geom_boxplot(aes(x = towater, y = v), notch=T)
```

## Model: Speed ~ temp

```{r model}
mod.speed = bam(v ~ s(distw, by = season2) + s(temp, by = season2, k = 4) + season2 + woody.density + s(id, bs = "re"), data = ele2)
```

## Fig 3b. Speed ~ distw

```{r ele.speed.distw}

ele.speed.distw = ele2 %>% mutate(v.pred = predict(mod.speed, newdata = ., scale = "response", allow.new.levels = T)) %>% filter(v > 0, round(temp) %in% 15:40) %>%  group_by(season2, distw_round = round_any(distw/1e3, 0.15)) %>%
  summarise(v.mean = mean(v), v.sd = sd(v), n.v = length(v), pred.mean = mean(v.pred, na.rm = T), pred.sd=sd(v.pred, na.rm = T), pred.n = length(v.pred)) %>%
  mutate(v.ci = qnorm(0.975)*v.sd/sqrt(n.v), ci.pred = qnorm(0.975)*pred.sd/sqrt(pred.n))
```


```{r plot.speed.distw}
#pdf(file = "fig5.pdf", width=4, height=4)

fig3b = 
ele.speed.distw %>%
  ggplot()+
# geom_line(aes(x = distw_round, y = pred.mean, col = season2), lty = 1)+
 # geom_ribbon(aes(x = distw_round, ymin = pred.mean-ci.pred, ymax = pred.mean+ci.pred), fill = "grey", alpha = 0.5)+
  geom_pointrange(aes(x = distw_round, y = v.mean, ymin = v.mean-v.ci, ymax = v.mean+v.ci, col = season2, shape = season2), fatten = 10, fill = "white", lty = 1, lwd = 0.2, stroke = 0.7)+
  scale_colour_manual(values = c(cola,colb))+
  scale_fill_manual(values = c(cola1,colb1))+
  scale_shape_manual(values=c(21,24))+
  theme_bw()+g1+
  xlim(0,7)+ylim(150,250)+
  labs(list(x = "Distance to water source (km)", y = "Speed (m/30 minutes)",
            col = "Season", fill = "Season"))
#  facet_wrap(~season2, ncol = 1, strip.position="right", scales="free_y")+theme(strip.text=element_blank(), strip.background=element_blank(), panel.spacing.y=unit)
```

## Fig 3c. Speed ~ temp

```{r ele.speed.temp.data}
#'
ele.speed.temp = ele2 %>% mutate(v.pred = predict(mod.speed, newdata = ., scale = "response", allow.new.levels = T)) %>% filter(v > 0, round(temp) %in% 15:40) %>%  group_by(season2, temp) %>%
  summarise(v.mean = mean(v), v.sd = sd(v), n.v = length(v), pred.mean = mean(v.pred, na.rm = T), pred.sd=sd(v.pred, na.rm = T), pred.n = length(v.pred)) %>%
  mutate(v.ci = qnorm(0.975)*v.sd/sqrt(n.v), ci.pred = qnorm(0.975)*pred.sd/sqrt(pred.n))
```

```{r plot_speed_temp}
#pdf(file = "fig4.pdf", height = 4, width=4)
#'plot begins here

fig3c = 
  ele.speed.temp %>%
  ggplot()+
  geom_smooth(aes(x = temp, y = pred.mean, col = season2, fill = season2), lty = 1, lwd = 0.5)+
 # geom_ribbon(aes(x = temp, ymin = pred.mean-ci.pred, ymax = pred.mean+ci.pred, fill = season2), alpha = 0.5)+
  geom_pointrange(aes(x = temp, y = v.mean, ymin = v.mean-v.ci, ymax = v.mean+v.ci, col = season2, shape = season2), fatten = 10, fill = "white", lty = 1, lwd = 0.2, stroke = 0.6)+
  scale_colour_manual(values = c(cola,colb))+
  scale_fill_manual(values = c(cola1,colb1))+
  scale_shape_manual(values=c(21,24))+
  theme_bw()+g1+
  labs(list(x = "Temperature (°C)", y = "Speed (m/30 minutes)",
            col = "Season", fill = "Season"))

dev.off()
```

----

# Fig 3.

```{r fig3}
#'plot all three figs

cairo_pdf(filename = "fig3.temp.speed.distw.pdf", height = 4, width = 12, fallback_resolution = 600)

grid.arrange(fig3a, fig3b, fig3c, nrow = 1)

dev.off()
```

