---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
source("libs.R")
source("ggplot.opts.r")
library(readr)

load("for-recurse.rdata")

ele.utm = ele.utm %>% dlply("id") %>% map(function(x) arrange(x, time)) %>% bind_rows() %>% plyr::arrange(id, time)

#source("elecode2.6dataloading.r")

load('eledata.rdata')
```


# load recurse csvs

```{r load data}
#'list files
#rev.stats = list.files(pattern = "recurse_")

#'load files
#rev.stats = lapply(rev.stats, read_csv)

#'keep the right files
#rev.stats = rev.stats[2:15]
```

```{r}
#'bind rows

#rev.stats = rev.stats %>% bind_rows()

#'save as rdata
#save(rev.stats, file = "rev.stats.rdata")
```

```{r}
load("rev.stats.rdata")
#'get season of entry
rev.stats$date = as.Date(rev.stats$entranceTime)

rev.stats = data.table(rev.stats)

a = data.table(ele.utm %>% group_by(date = as.Date(time)) %>% summarise(season = first(season2)) %>% ungroup() %>% select(date, season))

rev.stats = merge(rev.stats, a, by = "date")
```


## residence by time of day

```{r}
#'residence by hour

png(filename = "residence.hour.png", res = 400, height = 1600, width = 1600)

res.hour = rev.stats %>% mutate(hour = hour(entranceTime), residence = timeInside) %>% 
  group_by(hour, season) %>%
  summarise(mres = mean(residence), sdres = mean(residence), nres = length(residence)) %>% mutate(ci=qnorm(0.975)*sdres/sqrt(nres))
  
  ggplot(res.hour)+
  geom_pointrange(aes(x = hour, y = mres, ymin = mres-ci, ymax=mres+ci, col = season), fatten = 5, stroke = 0.6)+ scale_colour_manual(values = c(cola, colb))+
  g1+
    labs(list(x = "Hour of day", y = "Residence time (hrs)"))
  
dev.off()  
```

```{r}
png(filename = "revisittime.hist.png", res = 300, height = 800, width = 2400)

a1 = ggplot(rev.stats)+
  stat_density(aes(x = timeSinceLastVisit, col = season), geom="line")+ scale_colour_manual(values = c(cola, colb))+
  g1+
    labs(list(x = "Time since last visit (hrs)", y = "density"))+
    xlim(0,24)

a2 = ggplot(rev.stats)+
  stat_density(aes(x = timeSinceLastVisit, col = season), geom="line")+ scale_colour_manual(values = c(cola, colb))+
  g1+
    labs(list(x = "Time since last visit (hrs)", y = "density"))+
    xlim(0,240)

a3 = ggplot(rev.stats)+
  stat_density(aes(x = timeSinceLastVisit, col = season), geom="line")+ scale_colour_manual(values = c(cola, colb))+
  g1+
    labs(list(x = "Time since last visit (hrs)", y = "density"))+
    xlim(0,500)  

library(patchwork)

a1+a2+a3

dev.off()  
```


