---
output: html_document
editor_options: 
  chunk_output_type: console
---

# load libs

```{r}
source("libs.R")
source("libs.spatial.r")
```

# load rasters

```{r}
woodland = raster("trees_interpolate.tif")
tempday = raster("tempraster_day.tif")

temp_clip = raster("temp_clip.tif")

crs(woodland) = crs(tempday)
```

# crop rasters by kruger and extent

```{r}
#'get clipped.ext
clip.ext = st_read("spatial/kruger_clip_ext.shp")


#'mask
#woodland = mask(woodland, clip.ext)
tempday = mask(tempday, clip.ext)
temp_raster = mask(temp_clip, clip.ext)
clip.ext = st_transform(clip.ext, 4326)
landsat.temp = raster("~/git/elephants/ele_data/landsat7_temp_kruger.tif")
landsat.temp = mask(landsat.temp, clip.ext)

#'write
writeRaster(woodland, filename = "woodland_clip.tif","GTiff")
writeRaster(tempday, filename = "tempday_clip.tif","GTiff", overwrite = T)
writeRaster(landsat.temp, filename = "landsat_temp_clip.tif","GTiff")
writeRaster(temp_raster, filename = "temp_clip.tif","GTiff", overwrite = T)
```

