---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
getwd()
source("libs.R")
```

```{r read_all_eles}
library(readxl)

data = read_excel("../ele_data/AllEles2011_UTM.xlsx")
```

```{r make_spatial}
library(sf)

data_sf = st_as_sf(data, coords = c("XUTM","YUTM"))
st_crs(data_sf) = 32736
```

```{r read_skukuza}
skukuza = read_csv("generated_data/skukuza.csv")
skukuza = st_as_sf(skukuza, coords = c("long","lat"))
st_crs(skukuza) = 4326
skukuza = st_transform(skukuza, st_crs(32736))
```

```{r get_distance_to_skukuza}
data_sf$dist_skukuza = st_distance(data_sf, skukuza)
```

```{r filter_10km_points}
data.tow = data_sf %>% 
  mutate(dist_skukuza = as.numeric(dist_skukuza)) %>% 
  as.data.frame() %>% 
  filter(dist_skukuza <= 1e4)
```

```{r read_amb_temp}
amb_temp = list()
for(i in 1:7){
  amb_temp[[i]] = read_excel("../ele_data/Skukuza (Maria Thaker).xlsx",
                             sheet = i, col_names = T,skip = 1)
}

amb_temp = bind_rows(amb_temp) %>% 
  `colnames<-`(c("date","time","col3","temp.a","col5","col6","col7")) %>% 
  select(date, time, temp.a) %>% 
  mutate(time = as.POSIXct(paste(date, time, sep = " "))) %>% 
  select(time, temp.a)
```

```{r amb_temp_plot}
month_lab = function(x) month(x, label = T)
#'for plot
amb_temp.plot = amb_temp %>% mutate_at(vars(time), funs(hour,year, day, month_lab)) %>% mutate(temp.a = ifelse(temp.a < -5, NA, temp.a)) %>% filter(year %in% 2005:2011)

library(RColorBrewer);library(viridis)

#'plot
temp_skukuza = ggplot()+
  geom_tile(data = amb_temp.plot, aes(x = day, y = hour, fill = temp.a))+
  scale_fill_gradientn(colours = rev(brewer.pal(9, "RdYlBu")))+
  facet_grid(month_lab~year)+
  labs(list(x = "Day", y = "Hour", fill = "Ambient temp. (°C)"))+
  theme_bw()+theme(legend.position = "top",
                   strip.text.x = element_text(margin = margin(0.3,0,0.3,0, "mm")),
                   strip.text.y = element_text(margin = margin(0.4,0.4,0.4,0.4, "mm")))+
  scale_y_continuous(breaks = c(0,12,23))

#'save plot
ggsave(temp_skukuza, filename = "figs/fig08_temp_skukuza_long.pdf", width = 180/25.4, height = 180/25.4, device = pdf()); dev.off()
```

```{r clean_ele_data}
#'clean ele data
data.tow.clean = data.tow %>% 
  rename(date = Date_Time, temp = TempC ) %>% 
  mutate(time = as.POSIXct(as.numeric(date) + TimeNumber*24*60*60, origin = "1970-01-01"),
         time = floor_date(time, "30 min"))
```

```{r match_ele_data}
#'match ele and flux tower
data.tow.clean.ba = data.tow.clean %>% 
  select(id = UnitID, time, temp, season = Season) %>% 
  left_join(amb_temp) %>% 
  mutate(temp.a = ifelse(temp.a < -5, NA, temp.a)) %>% 
  filter(!is.na(temp), !is.na(temp.a)) %>% 
  mutate(hour = hour(time), season = as.factor(season),
         temp = as.numeric(temp))
```

```{r prep_for_BA}
mean2 = function(x) mean(x, na.rm = T)
data.tow.ba = data.tow.clean.ba %>% 
  group_by(id, hour, season) %>% 
  summarise_at(vars(temp,temp.a), funs(mean2)) %>% 
  mutate(mean.measures = (temp+temp.a)/2,
         diff.measures = temp-temp.a)
```


```{r random_eff_mod}
library(lme4)

mod.BA.ref = lmer(temp ~ temp.a + season + (1|id) + (1|hour), data = data.tow.ba)

summary(mod.BA.ref)
car::Anova(mod.BA.ref)
```

```{r BA_plot}

data.tow.ba = data.tow.ba %>% 
  ungroup() %>% 
  group_by(mean.measures = round(mean.measures), season) %>% 
  summarise_at(vars(diff.measures), funs(mean2))

ggplot()+
  geom_hline(yintercept = c(mean(data.tow.ba$diff.measures), 
                            mean(data.tow.ba$diff.measures) + 1.96*2.476,
                            mean(data.tow.ba$diff.measures) - 1.96*2.476),
             size = 0.1)+
  geom_point(data = data.tow.ba, aes(x = mean.measures, y = diff.measures, col = season), size = 3)+
  #geom_abline(slope = 1)+
  #facet_grid(id~season)+
  #scale_color_gradientn(colours = c(viridis::magma(12), rev(viridis::viridis(12))))+
  theme_classic()

ggsave(filename = "plot_BA_data_2005_2011_means.png", device = png(), dpi = 300); dev.off()
```

