---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r get_libs}
source("libs.R")
source("ggplot.pub.r")
```

```{r load_data}
#'load revisits data
load("ele.revisits.rdata")
```

# temp and mindw ~ landscape type

```{r load_vegclass_shp}
#'load soil data
library(sf)
veg = st_read("~/git/elephants/ele_data/gis_etc/Kruger Updated GIS Layers/landscapes_gertenbach1983.shp")

#veg$temp = extract(landsat.temp, veg, fun = mean, na.rm = T)
#'use rev data
#'convert to sf
ele.sf = st_as_sf(ele.rev, coords = c("xutm","yutm"), crs = 32736)
#'extract polygon values
ele.sf$veg = sp::over(as(ele.sf, "Spatial"), as(veg, "Spatial"))$LANDSCAPE
```

```{r load_landsat_temp}
library(raster)
#'load temp raster layer
landsat.temp = raster::raster("~/git/elephants/ele_code/spatial/landsat7_temp_utm36S.tif")

ndvi = raster("~/git/elephants/ele_code/spatial/kruger_ndvi.tif")

#'sample landsat temps and ndvi at ele.sf points
ele.sf$landsat_temp = raster::extract(landsat.temp, ele.sf)
ele.sf$ndvi = raster::extract(ndvi, ele.sf)
```

```{r get_temp_by_vegclass}
#'get data
vegclass.vars = as.data.frame(ele.sf) %>% filter(hour %in% 6:18) %>% dplyr::select(veg, temp, landsat_temp, season2) %>% melt(id.vars = c("veg","season2")) %>% filter(!is.na(veg)) 

#vegclass.vars = bind_rows(vegclass.vars, landsat.samples)

vegclass.vars$veg = droplevels(vegclass.vars$veg)

vegclass.vars$veg = factor(vegclass.vars$veg, levels=rev(levels(vegclass.vars$veg)))
  
a = data_frame(num = unique(as.character(as.numeric(vegclass.vars$veg))), y = -2, variable = "mindw", veg = (unique(vegclass.vars$veg))) %>% arrange(veg)

b = count(vegclass.vars, veg)

a = left_join(a, b, by = c("veg" = "veg"))
```

```{r fig03}
veg1 = 
  ggplot()+
  #geom_vline(xintercept = seq(from = 1.5, by = 1, length.out = nrow(a)), y = 35,lwd = 0.2,lty = 3,alpha = 1, col = 1)+
  
  geom_hline(data = vegclass.vars %>% 
               group_by(variable) %>% 
               summarise(mean = mean(value, na.rm=T)), 
             aes(yintercept = mean),
             #col = c(colb2, cola2, colb2, cola2), 
             lty = c(1,2), lwd = 0.2)+
  geom_boxplot(data = vegclass.vars,
               aes(x = veg, 
                   #group = c(veg, variable), 
                   y = value, fill = variable), 
               outlier.size = 0.1, 
               notch = T, width = 0.6, 
               position = position_dodge(width = 1),
               lwd = 0.2, coef = 1)+
  
  #facet_wrap(~season2)+
  #facet_wrap(~ifelse(variable == "temp", "Thermochron temp.", 
  #                   ifelse(variable == "mindw", "Dist. to water (km)", "LANDSAT-7 temp.")), scales = "free_x")+
  theme_pub()+
  coord_flip(
    ylim = c(15,40), xlim = c(0.2,18.5), expand = F
    )+
 scale_fill_manual(values = c("grey90", "white"), labels = c("thermochron (6am - 6pm)","LANDSAT-7"))+
  #scale_fill_gradient2(low = cols[1], high = cols[9], mid = "white")+
  scale_x_discrete(position = "top",
                   labels = c(paste(a$veg, " (n = ", a$n, ")", sep = "")))+
  theme(strip.text = element_text(size = 10, face = "plain"),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(),
        axis.text.y = element_text(hjust = 0),
        axis.line.x = element_line(size = 0.3),
        legend.position = "top", legend.box = "horizontal", legend.direction = "horizontal",legend.key = element_blank())+
  labs(list(x = "Landscape type", y = "Temperature (°C)",shape = "mean", fill = NULL))
```

```{r export_fig03}
#library(gridExtra)
pdf(file = "figs/fig03_landsat_thermochron_temps.pdf", height = 5, width = 7.087)
veg1

dev.off()
```

# Models: thermochron temperature as a function of landsat temp and vegclass

## get data

```{r model_thermochron_temp_landsat-temp}

#'prep data
ele = ele.sf; st_geometry(ele) = NULL; ele = ele %>% dplyr::select(temp, veg, id, hour, season2, landsat_temp) %>% mutate(id = as.factor(id)) %>% filter(hour %in% 6:18)
```

## run model

```{r}
library(lme4)
#'thermochron daily temps and vegetation class
mod.temp.veg = glmer(temp ~ sqrt(landsat_temp) + veg*sqrt(hour) + season2 + (1|id), data = ele, family = "poisson")
```

# ANOVA landsat temp ~ vegclass

```{r not_sure_what_this_is}
#'run a glm
glm.temp.veg = glm(round(landsat_temp) ~ veg, data = ele, family = "poisson")

summary(glm.temp.veg)
```

### interesting figures

```{r prep_data_exploratory_figs}
data = ele.sf %>% 
  `st_geometry<-`(NULL) %>% 
  unclass() %>% as.data.frame() %>% 
  #filter(hour %in% c(6:18)) %>% 
  dplyr::select(temp, veg, season2, landsat_temp, hour, ndvi, mindw, woody.density) %>% 
    mutate(day_phase = cut(hour, breaks = c(-0, 6, 10, 16, 18, 20, 23)),
        dayphase = mapvalues(day_phase, from = c(levels(day_phase)), to = c("midnight - 6am","6 - 10am","10am - 4pm","4 - 6pm","6 - 8pm","8pm - midnight"))) %>%
  group_by(dayphase) %>% 
  mutate(landsat_mean_temp = mean(landsat_temp,na.rm = T), 
         mean_temp = mean(temp, na.rm = T),
         temp_diff = temp - mean_temp,
         landsat_diff = landsat_temp - landsat_mean_temp,
         landsat_round_diff = round_any(landsat_diff, 0.5)) %>% 
  group_by(landsat_round_diff, season2, dayphase) %>% 
  summarise(mean_tdiff = mean(temp_diff, na.rm = T),
            sd_tdiff = sd(temp_diff, na.rm = T),
            n = length(temp_diff)) %>% 
  mutate(ci = qnorm(0.975)*sd_tdiff/sqrt(n)) %>% 
  filter(!is.na(dayphase))
```

```{r exploratory_fig_dayphase}
ggplot()+
    geom_vline(xintercept = 0, lwd = 0.2)+
    geom_hline(yintercept = 0, lwd = 0.2)+
  geom_pointrange(data = data %>% filter(!is.na(dayphase)), aes(x = landsat_round_diff, y = mean_tdiff, ymin = mean_tdiff - ci, ymax = mean_tdiff + ci, shape = season2, col = season2), position = position_dodge(width = 0.5), fill = "white", size = 0.3)+
    
  #  geom_label(aes(x = c(-2.5,-2.5,2.5,2.5),
  #                y = c(2,-1,2,-1),
  #                label = c("thermal landscape selection", "env. tracking","env. tracking","thermal landscape selection"), hjust = "center"), size = 2)+
    
    scale_colour_manual(values = c(cola, colb))+
    scale_shape_manual(values = c(21,24))+
    theme_pub()+
  facet_wrap(~dayphase, scales = "free")+
  coord_cartesian(ylim = c(-2.5,2.5), xlim = c(-5,5))+
      theme(strip.background = element_rect(fill = "grey90"))+
    labs(list(x = "point LANDSAT temp — mean LANDSAT temp (°C)", y = "point thermochron temp — mean thermochron temp (°C)"))

```

### even more fun plots

```{r}
data2 = ele.sf %>% 
  `st_geometry<-`(NULL) %>% 
  unclass() %>% as.data.frame() %>% 
  #filter(hour %in% c(6:18)) %>% 
  dplyr::select(temp, veg, season2, landsat_temp, hour, mindw, ndvi, woody.density) %>% 
   mutate(day_phase = cut(hour, breaks = c(-0, 6, 10, 16, 18, 20, 23)),
         dayphase = mapvalues(day_phase, from = c(levels(day_phase)), to = c("midnight - 6am","6 - 10am","10am - 4pm","4 - 6pm","6 - 8pm","8pm - midnight"))) %>% 
  mutate(landsat_mean_temp = mean(landsat_temp,na.rm = T), 
         mean_temp = mean(temp, na.rm = T),
         temp_diff = temp - mean_temp,
         landsat_diff = landsat_temp - landsat_mean_temp,
         landsat_round_diff = round_any(landsat_diff, 0.1),
         temp_round_diff = round_any(temp_diff, 0.1)) %>% 
  group_by(landsat_round_diff, temp_round_diff, dayphase) %>% 
  summarise(mindw = mean(mindw, na.rm = T),
            woody = mean(woody.density, na.rm = T),
            ndvi = mean(ndvi, na.rm = T)) %>% 
  filter(!is.na(dayphase))
```

# LANDSAT -- thermochron regression line and residuals

```{r temp_landsat_regression}
library(lme4)
#'run model
mod.temp.measures = glmer(temp ~ sqrt(landsat_temp)*log(mindw) + veg + season2 + (1|id) + (1|hour), data = as.data.frame(ele.sf) %>% filter(hour %in% c(6:18), temp %in% c(14:40)), family = "poisson", na.action=na.exclude)

save(mod.temp.measures, file = "generated_data/mod.temp.measures.rdata")
```

```{r}
#'predict values and get residuals
ele = as.data.frame(ele.sf) %>% filter(hour %in% c(6:18),temp %in% c(14:40))

data3 = ele %>% 
  mutate(tempred = predict(mod.temp.measures, newdata = ele, allow.new.levels = T, type = "response"),
         residual = resid(mod.temp.measures, na.action=na.exclude),
         landsat_diff = landsat_temp - mean(landsat_temp, na.rm = T),
         landsat_round_diff = round_any(landsat_diff, 0.25),
         landsat_round = round_any(landsat_temp, 0.5)) %>%
  group_by(landsat_round,season2) %>% 
  summarise(mean.r = mean(residual, na.rm = T),
            sd.r = sd(residual, na.rm = T),
            n.r = length(residual)) %>% 
  mutate(ci = qnorm(0.975)*sd.r/sqrt(n.r))
```

```{r}
ggplot()+
  geom_vline(xintercept = mean(ele$landsat_temp, na.rm = T), lwd = 0.2, col = 1)+
  geom_hline(yintercept = 0, lwd = 0.2, col= 1)+
  geom_text(aes(x = mean(ele$landsat_temp, na.rm = T), y = 1, label = "GLMM: \n thermochron temp ~ \n LANDSAT-7 temp + hour of day+ \n Random effects: \n elephant ID + vegetation type"), size = 2, hjust = "left", vjust = "inward")+
  geom_pointrange(data = data3,
                  aes(x = landsat_round, y = mean.r, ymin = mean.r - ci, ymax = mean.r + ci, col = season2), position = position_dodge(width = 0.2), size = 0.2)+
  scale_color_manual(values = c(cola2, colb2))+
  theme_pub()+
  coord_cartesian(ylim = c(-0.5,1))+
  labs(list(x = "LANDSAT-7 temp. (°C)",
            y = "Model residuals"))

```

# residuals vs LANDSAT temp model

```{r}
#'get the data for the model: residuals and predicted temps
#data4 = 
ele %>% 
  mutate(tempred = predict(mod.temp.measures, newdata = ele, allow.new.levels = T, type = "response"),
         residual = resid(mod.temp.measures, na.action=na.exclude)) %>% 
  group_by(a = round_any(landsat_temp, 0.25),
           b = round_any(residual, 0.25)) %>%
  summarise(mindw = mean(mindw, na.rm = T)) %>% 
  
  ggplot()+
  geom_tile(aes(x = a, y = b, fill = mindw), alpha = 1)+
  geom_vline(xintercept = mean(ele$landsat_temp, na.rm = T), lwd = 0.2, col = 1)+
  geom_hline(yintercept = 0, lwd = 0.2, col= 1)+
  geom_pointrange(data = data3,
                  aes(x = landsat_round, y = mean.r, ymin = mean.r - ci, ymax = mean.r + ci, col = season2), position = position_dodge(width = 0.2), size = 0.5, shape = 16)+
  scale_color_manual(values = c(cola2, colb2))+
  scale_fill_viridis()+
  coord_cartesian(ylim = c(-02,2))+
  labs(list(x = "LANDSAT-7 temp. (°C)",
            y = "Model residuals", fill = "distance \n to \n water (m)"))+
  theme_pub()+theme(legend.position = "right", legend.key = element_blank())
```

```{r}
#'run the model
mod.tempresid.landsat = glm(residual ~ landsat_temp+season, data = data4)

library(segmented)

mod.resid.segments = segmented(mod.tempresid.landsat, seg.Z = ~landsat_temp, psi = c(25, 28))

```


