---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load libs
  
```{r load_libs, message=FALSE, warning=FALSE}
#set env
library(tidyverse)
```

```{r read_all_eles}
library(readxl)

data = read_excel("../ele_data/AllEles2011_UTM.xlsx")
```

```{r make_spatial}
library(sf)

data_sf = st_as_sf(data, coords = c("XUTM","YUTM"))
st_crs(data_sf) = 32736
```

```{r read_skukuza}
skukuza = read_csv("generated_data/skukuza.csv")
skukuza = st_as_sf(skukuza, coords = c("long","lat"))
st_crs(skukuza) = 4326
skukuza = st_transform(skukuza, st_crs(32736))
```

```{r get_distance_to_skukuza}
data_sf$dist_skukuza = st_distance(data_sf, skukuza)
```

```{r filter_10km_points}
data.tow = data_sf %>% 
  mutate(dist_skukuza = as.numeric(dist_skukuza)) %>% 
  as.data.frame() %>% 
  filter(dist_skukuza <= 1e4)
```

```{r read_amb_temp}
amb_temp = list()
for(i in 1:7){
  amb_temp[[i]] = read_excel("../ele_data/Skukuza (Maria Thaker).xlsx",
                             sheet = i, col_names = T,skip = 1)
}

amb_temp = bind_rows(amb_temp) %>% 
  `colnames<-`(c("date","time","col3","temp.a","col5","col6","col7")) %>% 
  select(date, time, temp.a) %>% 
  mutate(time = as.POSIXct(paste(date, time, sep = " "))) %>% 
  select(time, temp.a)

```

```{r clean_ele_data}
#'clean ele data
data.tow.clean = data.tow %>% 
  rename(date = Date_Time, temp = TempC ) %>% 
  mutate(time = as.POSIXct(as.numeric(date) + TimeNumber*24*60*60, origin = "1970-01-01"),
         time = floor_date(time, "30 min"))
```

```{r match_ele_data}
#'match ele and flux tower
data.tow.clean.ba = data.tow.clean %>% 
  select(id = UnitID, time, temp, season = Season) %>% 
  left_join(amb_temp) %>% 
  mutate(temp.a = ifelse(temp.a < -5, NA, temp.a)) %>% 
  filter(!is.na(temp), !is.na(temp.a)) %>% 
  mutate(hour = hour(time), season = as.factor(season),
         temp = as.numeric(temp))
```

```{r load_ggplot_theme}
#'source script
#load("eledata.rdata")
source('ggplot.pub.r')
```

```{r}
save(ele.tow, ele.tow02, towtemp, fig_temp_measure_hour, file = "/home/pratik/git/elephants/ele_data/ele.tower.rdata")
```

# Plot temp ~ hour

```{r temp_hour_plot}
ci = function(x) 1.96*sd(x, na.rm = T)/sqrt(length(x))
#### make figure of temps per hour of day
#load("../ele_data/ele.tower.rdata")
data_fig3a = data.tow.clean.ba %>% 
  group_by(hour, season) %>% 
  summarise_at(vars(temp, temp.a), vars(mean, ci)) 

fig_temp_measure_hour <- 
ggplot(data_fig3a, aes(x = hour))+
    
  geom_rangeframe(data = data_frame(x = c(0,23), y=c(15,40)), aes(x,y))+
  
  geom_path(aes(y = temp_mean, col = season), lty = 1)+

  geom_path(aes(y = temp.a_mean, col = season), lty=2)+
  
  geom_ribbon(aes(ymin = temp_mean - temp_ci, ymax = temp_mean + temp_ci, group = season, fill = season), alpha = 0.2)+

  geom_ribbon(aes(ymin = temp.a_mean - temp.a_ci, ymax = temp.a_mean + temp.a_ci, group = season, fill = season), alpha = 0.2)+

  
  scale_colour_brewer(palette = "Set1")+
  scale_fill_brewer(palette = "Set1")+
  #scale_shape_manual(values = c(21,24))+
  coord_cartesian(xlim = c(0,23))+
  scale_x_continuous(breaks = c(0,4,8,12,16,20,23))+
  scale_y_continuous(breaks = seq(15,40,5))+
  theme_pub()+
  labs(list(x = "Hour of day", y = "Temperature (°C)", title = "(a)"))

```

# GLMM collar ~ ambient temp

```{r}
library(lme4)
mean_wo_na = function(x) mean(x, na.rm=T)
sd_wo_na = function(x) sd(x, na.rm = T)
#mod.temp.measures = lmer(temp ~ temp.a + season2 + (1|id) + (1|hour), data = ele.tow)

#summary(mod.temp.measures)
#car::Anova(mod.temp.measures)
library(stringi)
#'random effects model for within individual and hour std deviation
#'get the mean data
ele.BA.data = data.tow.clean.ba %>% ungroup()%>% 
  mutate(diff = temp-temp.a, mean.temp = (temp+temp.a)/2) %>% 
  mutate(hour.plot = paste(stri_pad(hour, 2, side = "left", pad = "0"), ":00", sep = ""))

#'run mods in each hour
ele.BA.mods = ele.BA.data %>% ungroup()%>% 
  dlply("hour.plot") %>% 
  map(function(x){
    lmer(temp ~ temp.a + season + (1|id), data = x)
  })

#'prep predict data
ele.pred.data = ele.BA.data %>% dlply("hour.plot")

#'model fit
ele.tempmod.fit = map2(ele.pred.data, ele.BA.mods, function(x,y){
  x %>% mutate(pred = predict(y, newdata =x, type = "response", se.fit = T))
}) %>% bind_rows()

ele.ba.summary = ele.BA.mods %>% map(VarCorr) %>% 
  map(function(x){
    data_frame(sd_id = as.data.frame(x) %>% .$sdcor %>% sum())
}) %>% bind_rows() %>% mutate(hour = 0:23) %>% 
  mutate(hour.plot = paste(stri_pad(hour, 2, side = "left", pad = "0"), ":00", sep = ""))

mean_diff = ele.BA.data %>% group_by(hour.plot) %>% summarise(diff = mean(diff, na.rm = T)) %>% left_join(ele.ba.summary)

library(ggthemes)
source("ggplot.pub.r")

#'make appendix figure a
fig_app_01 = 
  ggplot()+
  geom_rangeframe(data = data_frame(x=c(10,40), y = c(0,40)), aes(x,y))+
  geom_point(data = ele.BA.data, aes(x = temp.a, y = temp), size = 0.1, alpha = 0.2)+
  geom_smooth(data = ele.tempmod.fit, aes(x = temp.a, y = pred), method = "glm", col = colb2)+
  geom_abline(slope = 1, lty = 2, col = 1, lwd = 0.2)+
    
   # geom_vline(xintercept = c(20), col = cola2, lwd = 0.2)+
    #geom_hline(yintercept = c(20), col = cola2, lwd = 0.2)+
  scale_x_continuous(breaks = c(10,25,40))+
  facet_wrap(~hour.plot, nrow = 4)+
    theme_pub()+
  theme(strip.text = element_text(face = "bold"))+
      labs(list(x = "Ambient temperature (°C)", y = "Collar temperature (°C)", title = "(a)"))

#ggsave(fig_app_01, filename = "figs/fig07_app_01_temp_reln_hour.pdf", device = pdf(), height = 180/25.4, width = 90/25.4); dev.off()

#'appendix figure b
fig_app_02 = 
  ggplot()+
  geom_rangeframe(data = data_frame(x=c(10,40), y = c(-10,30)), aes(x,y))+
  geom_point(data = ele.BA.data, aes(x = mean.temp, y = diff), size = 0.1, alpha = 0.2)+
 # geom_smooth(data = ele.tempmod.fit, aes(x = temp.a, y = pred), method = "glm", col = 2, fill = 2)+
  geom_abline(slope = 0, lty = 2, col = 1, lwd = 0.2)+
  geom_hline(data = mean_diff, aes(yintercept = diff), col= colb2)+
  geom_hline(data = mean_diff, aes(yintercept = 1.96*sd_id + diff), col = cola2)+
  geom_hline(data = mean_diff, aes(yintercept = diff - 1.96*sd_id), col = cola2)+
  #coord_cartesian(ylim = c(0,40), xlim = c(0,40))+
  scale_y_continuous(breaks = seq(-10,30, 10))+
  
  scale_x_continuous(breaks = c(10,25,40))+
 # scale_color_brewer(palette = "Set2")+
  facet_wrap(~hour.plot, nrow = 4)+
  theme_pub()+
  theme(strip.text = element_text(face = "bold"))+
      labs(list(x = "Mean (amb & collar) temp. (°C)", y = "Collar - amb. temp. (°C)", title = "(b)"))

fig07_appendix = gridExtra::grid.arrange(fig_app_01, fig_app_02, nrow = 1)

ggsave(fig07_appendix, filename = "figs/fig07_app_02_temp_reln_hour.pdf", device = pdf(), height = 180/25.4, width = 180*1.2/25.4); dev.off()
```


# Scatterplot

```{r scatterplot}
#'plot scatterplot

#### to be replaced by a bland altman plot?
#'run lmm
library(lme4)
mod.temp = lmer(temp ~ temp.a + season + (1|hour) + (1|id), data = data.tow.clean.ba)
#'get summary
summary(mod.temp)
car::Anova(mod.temp)

#'variances
#'Random effects
var_eff_hour = as.numeric(VarCorr(mod.temp))[1]
var_eff_Id = as.numeric(VarCorr(mod.temp))[2]
#'1st = hour, 2nd = ID
var_eff_hour

var_eff_Id

#'Residual
var_res = as.numeric(attr(VarCorr(mod.temp), "sc")^2)
var_res

#'Fixed effects only
var_fix = var(predict(lm(temp ~ temp.a + season, data = data.tow.clean.ba)))
var_fix

#'Total data variance
var_tot = var(data.tow.clean.ba$temp)

#'Sum of model variances
var_eff_hour + var_eff_Id + var_res + var_fix

#'Percentages
c(var_eff_hour, var_eff_Id, var_res, var_fix)*100/var_tot

fig_temp_rel_data <- data.tow.clean.ba %>% #filter(dist.tow <= 1e4) %>% 
  group_by(season, temp.a = round(temp.a)) %>%
  summarise_at(vars(temp), funs(temp_mean = mean, temp_ci = ci))
  
fig_temp_measure_relation <- 
ggplot()+
  geom_smooth(data = fig_temp_rel_data, aes(x = temp.a, y = temp_mean, group = season, col = season, fill = season), method = "glm", show_guide = F,se =T, alpha = 0.2,lwd = 0.5)+
  
  geom_pointrange(data = fig_temp_rel_data, aes(x = temp.a, y =  temp_mean, ymin = temp_mean-temp_ci , ymax = temp_mean+temp_ci, shape = season, col = season), position = position_dodge(width = 0.5), fill = "white", size = 0.1, stroke = 0.4)+
  geom_rangeframe(data = data_frame(x = c(5,40), y = c(4,44)), aes(x,y))+
  
  geom_abline(slope = 1, lty = 2)+

  scale_colour_brewer(palette = "Set1")+
  scale_fill_brewer(palette = "Set1")+
  scale_shape_manual(values = c(21, 24))+
  scale_x_continuous(breaks = seq(5,40,5))+
  scale_y_continuous(breaks = seq(4,44,4))+
  #scale_linetype_manual(values = c(2,1))+
  theme_pub()+
  coord_cartesian(xlim=c(5,40), ylim = c(5,44))+
  #coord_cartesian(xlim = c(0,40), ylim = c(0,40))+
  labs(list(x = "Ambient temperature (°C)", y = "Collar temperature (°C)", title = "(b)"))

#ggsave(filename = "fig01_b.png", fig01_b, device = png())
```

```{r fig_ba_revised}
#'egt data ofr general BA plot
ele.BA.data = ele.BA.data %>% 
  filter(!is.na(temp), !is.na(temp.a)) %>% 
  ungroup() %>% 
  group_by(id, hour, season) %>% 
  summarise_at(vars(temp, temp.a), funs(mean)) %>% 
  mutate(mean.measures = (temp+temp.a)/2,
         diff.measures = temp-temp.a) %>% 
  ungroup() %>% 
  group_by(mean.measures = round(mean.measures), season) %>% 
  summarise_at(vars(diff.measures), funs(mean))

#'general gamm differences vs mean
library(mgcv)
BA.gam = gam(diff.measures ~ s(mean.measures, by = season), data = ele.BA.data)
#'summary
summary(BA.gam)

#'get predictions
ele.BA.data$pred = predict(BA.gam, type = "response", newdata = ele.BA.data, se.fit = T)[[1]]
ele.BA.data$se = predict(BA.gam, type = "response", newdata = ele.BA.data, se.fit = T)[[2]]

figBArevised = 
ele.BA.data %>%   
  ggplot()+
  
  geom_ribbon(aes(x = mean.measures, ymin = pred-se, ymax = pred+se, fill = season), alpha = 0.2)+
  geom_line(aes(x = mean.measures, y = pred, col = season), lty = 2)+
  
  geom_point(aes(x = mean.measures, y = diff.measures, col = season, shape = season), fill = "white", size = 1,stroke = 0.5)+
  scale_color_brewer(palette = "Set1")+
  scale_fill_brewer(palette = "Set1")+
  scale_shape_manual(values = c(21,24))+
  geom_rangeframe(data = data_frame(x=c(15,35), y = c(-5,20)), aes(x,y))+
  
  geom_hline(yintercept = c(0,mean(mean_diff$diff),  
                            mean(mean_diff$diff) + 1.96*mean(mean_diff$sd_id),
                            mean(mean_diff$diff) - 1.96*mean(mean_diff$sd_id)), lty = c(2,1,1,1), lwd = c(0.2, 0.4,0.4,0.4), col = c(1,colb,cola,cola))+
    
  
  
  theme_pub()+
  scale_y_continuous(breaks = c(seq(-5,20, 5)))+
  
  labs(list(x = "Mean (collar & amb.) temp (°C)", y = "Collar temp. - amb. temp. (°C)", title = "(c)"))
```


# Figure 3

```{r}
half = 85/25.4;full = 180/25.4
#'export fig for temp measures
library(gridExtra)

pdf(file = "figs/fig03temp_measures.pdf",height = half, width = full)
#png(filename = "fig_thermochron_data.png",height = 1600, width = 3200, res = 400)

grid.arrange(fig_temp_measure_hour, fig_temp_measure_relation, figBArevised, nrow = 1)

dev.off()
```

```{r hourly_model_output}
#'hourly model output
ele.temp.mods.summary = ele.BA.mods %>% 
  map(summary) %>% 
  map(function(x){x$coefficients %>% 
      as.data.frame() %>% 
      select(Estimate, `t value`) %>% 
      mutate(predictor = rownames(.)) %>% 
      gather(lmm_output, value, -predictor) %>% filter(predictor != ("(Intercept)")) %>% 
      mutate(value = plyr::round_any(value, 0.01)) %>% 
      spread(lmm_output, value)}) %>% 
  bind_rows() %>% 
  mutate(hour = rep(0:23, each = 2), predictor = ifelse(predictor != "temp.a", "season", predictor)) %>% 
  
  left_join(map(ele.BA.mods, function(x){car::Anova(x) %>% 
      as.data.frame() %>% 
      mutate(predictor = rownames(.)) %>% 
      rename(p_value = `Pr(>Chisq)`) %>% 
      select(-Df)}) %>% 
        bind_rows() %>% 
        mutate(hour = rep(0:23, each = 2), Chisq = plyr::round_any(Chisq, 0.1), p_value = plyr::round_any(p_value, 0.001)))
```

```{r export_temp_mod_summary}
#'export to csv
write_csv(ele.temp.mods.summary, path = "../ele_data/ele_temp_mods_summary.csv")

```

