---
output: html_document
editor_options: 
  chunk_output_type: console
---

# identifying loops

```{r}
source("libs.R")
source("ggplot.opts.r")
```

```{r}
load("ele.revisits.rdata")
```

# find high rev and low distance to water

```{r}
#'quantiles
quantile(ele.rev$angle, na.rm = T)

ele.rev$watervisits = ifelse(ele.rev$mindw <=500 & ele.rev$residence >=10 & ele.rev$revisits >= 10, 1, 0)

#ggplot(ele.rev)+ geom_smooth(aes(x = mindw, y = residence/revisits))+
  #coord_cartesian(xlim = c(0,5e2), ylim = c(1.5,1.65))

#a = ele.rev %>% filter(watervisits == 1, !is.na(waterdiff)) %>% select(id, xutm, yutm, v, angle, mindw, revisits, residence, fpt, waterdiff)

#write.csv(a, file = "ele.watervisits.csv", row.names = F)
```

# find water visits by each ele

```{r}
#'separate by ele, and find the time between consecutive watervisits

ele3 = ele.rev %>% dlply("id") %>%
  map(function(x) x %>% filter(watervisits == 1))

for(i in 1:14){
  ele3[[i]]$wvint = as.numeric(difftime(ele3[[i]]$time[-1], ele3[[i]]$time, units = "hours"))
}

ele3 = bind_rows(ele3)

```

# plot time between water visits

```{r}
#'remove bad difftimes
ele4 = ele3 %>% filter(wvint > 0, wvint < 72)
```


## fig 2b

```{r ele_looping}
#fig2a = 
ggplot(ele7)+
  stat_density(aes(x = between_point_dist/1e3, col = season), geom = "line", position = "identity", lwd = 0.7)+
  scale_colour_manual(values = c(cola, colb))+
  g1+
  labs(list(x = "Displacement (km)", title = "(a)"))+
  xlim(0,5)
```

# Begin processing for 24 - 48 hour tracks

```{r}
#'remove points with low residence, and less than 3 hours apart
ele4 = ele3 %>% filter(wvint >= 40, wvint <= 50)
```

## anti-join

```{r}
#'remove all matches in ele4
ele.rev = anti_join(ele.rev, ele4, by = c("id", "time"))

ele.rev$watervisits = 0; ele.rev$wvint = NA
```

```{r}
#'rejoin
ele5 = rbind(ele.rev, ele4)

#'sort by id and time

ele5 = ele5 %>% arrange(id, time)
```

## assign loop

```{r}

#'split by ele and id loops
ele5  = ele5 %>% dlply("id") %>%
  map(function(x){
    x %>% mutate(loop = cumsum(watervisits))
  })

```

```{r}
ele6 =  ele5 %>%
  map(function(x){
    x %>% group_by(loop) %>% mutate(looptime = as.numeric(difftime(time, time[1], units = "hours")), deltadw = mindw - mindw[1], tempchange = temp - temp[1], ambtempdiff = c(NA, diff(temp))) %>% filter(looptime < 50) %>% mutate(loopprop = looptime/max(looptime))
  })
```


## whats's happening in loops?

```{r}
#'loop data summary
loopdata = ele6 %>%
  bind_rows() %>%
  filter(looptime < 50) %>%
  select(loopprop, mindw, waterdiff, temp, fpt, loop, season2, v, tempchange, woody.density, hour, ambtempdiff)

# loopdata %>%
#  ggplot()+
#  geom_smooth(aes(x = loopprop, y = ambtempdiff, col = season2, fill = season2), lty = 1, se = T, lwd = 0.5, method = "gam", formula = y ~ s(x, bs = "cc", k = 6))+g1+
#  scale_color_manual(values = c(cola, colb))+
#    scale_fill_manual(values = c(cola1, colb1))

loopdata2 =loopdata %>% ungroup() %>% select(loopprop, mindw, temp, v, season2) %>%  group_by(season2, loopprop = round_any(loopprop, 0.05)) %>% melt(id.vars = c("season2", "loopprop")) %>% group_by(season2, loopprop, variable) %>% summarise(mean = mean(value, na.rm=T), sd = sd(value, na.rm = T), n = length(value)) %>% mutate(ci = qnorm(0.975)*sd/sqrt(n)) 
```

```{r}
png(filename = "loopvalues.48hr.png", res = 300, width = 2400, height = 1200)
loopdata2 %>%
  
  ggplot()+
  geom_pointrange(aes(x = loopprop, y = mean, ymin = mean-ci, ymax = mean+ci,  col = season2, fill = season2, shape = season2), lty = 1, se = T, lwd = 0.5, fatten = 5, stroke = 0.6, position = position_dodge(width = 0.2))+
  scale_color_manual(values = c(cola, colb))+
    scale_fill_manual(values = c(cola1, colb1))+
    labs(list(x = "Track stage", y = "Value"))+
  scale_x_continuous(breaks = seq(0,1,0.5), labels = c("Start", paste(50,"%", sep=""), "End"))+
  facet_wrap(~variable, scales = "free")+
  g1

dev.off()
```



# 24 - 48 hour loops

```{r}
library(sp)

#'split by id and season

ele.lines = ele6 %>% bind_rows() %>% arrange(id, time) %>%  dlply(c("id","loop")) %>%
  map(function(x) Line(cbind(x$xutm, x$yutm)))

ele.lines = ele.lines %>%
  map(function(x) Lines(x, ID = "a"))

for(i in 1:length(ele.lines)){
  ele.lines[[i]]@ID = names(ele.lines)[i]
}

names = names(ele.lines)

ele.lines = SpatialLines(ele.lines, proj4string = CRS("+proj=utm +zone=36 +south +datum=WGS84 +units=m +no_defs"))

library(stringi)

data = data.frame(cbind(id = 1:length(ele.lines), name = names, ele = stri_extract(names, regex='[^.]*'), loop = as.numeric(sub('.*\\.', '', names))))

data$loop = as.numeric(as.character(data$loop))

rownames(data) = names

ele.lines = SpatialLinesDataFrame(ele.lines, data = data)

#'export
library(rgdal)
writeOGR(ele.lines, dsn = ".", layer = "ele.loops48", driver = "ESRI Shapefile", overwrite_layer = T)
```