# Ele lines

```{r}
load("eles_basic.rdata")
load("ele_after_move.rdata")

ele2 = ele2 %>% mutate(id = as.factor(from.idData.rep.1..n.locs.from.....)) %>% dplyr::select(id, time, distance,v, speed)

ele = ele %>% inner_join(ele2)

source("libs.R")
```


```{r}
library(sp)

#'split by id and season

ele.lines = ele %>% arrange(id, time) %>% mutate(year = year(time)) %>%  dlply(c("id","season2","year")) %>% 
  map(function(x) Line(cbind(x$long, x$lat)))

ele.lines = ele.lines %>% 
  map(function(x) Lines(x, ID = "a"))

for(i in 1:length(ele.lines)){
  ele.lines[[i]]@ID = names(ele.lines)[i]
}

names = names(ele.lines)

ele.lines = SpatialLines(ele.lines, proj4string = CRS("+proj=longlat +datum=WGS84 +no_defs"))

library(stringi)

data = data.frame(cbind(id = 1:length(ele.lines), name = names, ele = stri_extract(names, regex='[^.]*'), season = unlist(stri_extract_all_regex(names, '\\p{Ll}+'))))

rownames(data) = names

ele.lines = SpatialLinesDataFrame(ele.lines, data = data)

#'export
library(rgdal)
writeOGR(ele.lines, dsn = ".", layer = "ele.lines.longlat", driver = "ESRI Shapefile", overwrite_layer = T)
```

# Ele loops


```{r}
library(sp)

#'split by id and season

ele.lines = ele.data %>% arrange(id, time) %>%  dlply(c("id","loop")) %>%
  map(function(x) Line(cbind(x$xutm, x$yutm)))

ele.lines = ele.lines %>%
  map(function(x) Lines(x, ID = "a"))

for(i in 1:length(ele.lines)){
  ele.lines[[i]]@ID = names(ele.lines)[i]
}

names = names(ele.lines)

ele.lines = SpatialLines(ele.lines, proj4string = CRS("+proj=utm +zone=36 +south +datum=WGS84 +units=m +no_defs"))

library(stringi)

data = data.frame(cbind(id = 1:length(ele.lines), name = names, ele = stri_extract(names, regex='[^.]*'), loop = as.numeric(sub('.*\\.', '', names))))

data$loop = as.numeric(as.character(data$loop))

#'join with other loopdata!
data = data %>% left_join(ele.all.segments, by = c("ele" = "id", "loop"))

rownames(data) = names

ele.lines = SpatialLinesDataFrame(ele.lines, data = data)

#'export
library(rgdal)
writeOGR(ele.lines, dsn = "spatial/long_loops", layer = "ele.departure.segs", driver = "ESRI Shapefile", overwrite_layer = T)
```

```{r}
library(sp)

#'split by id and season

ele.lines = ele.all.segments %>%  dlply(c("id","loop")) %>%
  map(function(x) Line(rbind(cbind(x$x1, x$y1), cbind(x$x2, x$y2))))

ele.lines = ele.lines %>%
  map(function(x) Lines(x, ID = "a"))

for(i in 1:length(ele.lines)){
  ele.lines[[i]]@ID = names(ele.lines)[i]
}

names = names(ele.lines)

ele.lines = SpatialLines(ele.lines, proj4string = CRS("+proj=utm +zone=36 +south +datum=WGS84 +units=m +no_defs"))

library(stringi)

data = data.frame(cbind(id = 1:length(ele.lines), name = names, ele = stri_extract(names, regex='[^.]*'), loop = as.numeric(sub('.*\\.', '', names))))

data$loop = as.numeric(as.character(data$loop))

#'join with other loopdata!
data = data %>% left_join(ele.all.segments, by = c("ele" = "id", "loop"))

rownames(data) = names

ele.lines = SpatialLinesDataFrame(ele.lines, data = data)

#'export
library(rgdal)
writeOGR(ele.lines, dsn = "spatial/long_loops", layer = "ele.segments.displacements", driver = "ESRI Shapefile", overwrite_layer = T)
```