# Load libs and data

```{r}
#'load libs and ele data
source("libs.R");source("ggplot.opts.r")
source("ele.move.r")

#'load ssf functions
source("ssf-codes.R")
```


## Loading more packages

```{r}
library(raster)
library(rgdal)
library(ggmap)
library(survival)
library(TwoStepCLogit)
library(pbs)
library(dplyr)
library(lubridate)
library(move)
library(MASS)
library(fdrtool)
library(circular)
library(CircStats)
```

## Environmental data: topography, waterways, and NDVI

```{r}
library(sf)
rivers = st_read("~/git/elephants/ele_data/gis_etc/Kruger Updated GIS Layers/rivers_main.shp")

st_crs(rivers) = proj4string(ele.move)

wh = st_read("~/git/elephants/ele_data/gis_etc/Kruger Updated GIS Layers/waterpoints_zambatis_2011.shp")

#plot(wh, col = wh$CURRENT)

wh = wh %>% filter(CURRENT=="Open")
```

```{r}
#'100m sampling grid from ele move extents
#'make topology
grid.topo = GridTopology(cellcentre.offset = bbox(ele.move)[,1]+c(100,100)/2, cellsize = c(100,100), cells.dim = ceiling(diff(t(bbox(ele.move)))/c(100,100)))

#'make grid
grid = SpatialGrid(grid.topo, proj4string = proj4string(as(rivers, "Spatial")))

#'convert to spatial points
grid = as(grid, "SpatialPoints")

```

```{r}
#'get dist to waterholes
grid.dwh = apply(X = spDists(grid, as(wh, "Spatial")), 1, min)

#'dist to rivers
library(rgeos)
grid.dri = apply(X = gDistance(as(rivers, "Spatial"), grid, byid = T), 1, min)

#'mindw
grid$mindw = apply(cbind(grid.dri, grid.dwh),1,min)
```

```{r}
#'make matrix then raster
water.raster = raster(matrix(grid$mindw, nrow = 1550, ncol = 782, byrow = T))
#'set extent
extent(water.raster) = extent(ele.move)
crs(water.raster) = crs(ele.move)
writeRaster(water.raster, "waterraster.tif", format="GTiff", overwrite=T)

```

```{r}
library(RColorBrewer)

pdf(file = "distance_water_raster.pdf", height = 5, width = 5)
plot(water.raster, col = colorRampPalette(rev(brewer.pal(9, "YlGnBu")))(20))
lines(as(rivers, "Spatial"), col = "white")
points(as (wh, "Spatial"), col = "white")
dev.off()


```

# Get temperature raster

```{r}
#'sample only daytime eles
ele.temp = ele2 %>% filter(hour %in% 9:15) %>% group_by(x = round_any(xutm, 100), y = round_any(yutm, 100)) %>% summarise(temp = mean(temp))

#'write to shapefile
coordinates(ele.temp)=~x+y
crs(ele.temp) = crs(water)


library(maptools)
writeOGR(ele.temp, dsn = "spatials", driver = "ESRI Shapefile", layer = "ele.temp")
```


```{r eval=FALSE, include=FALSE}
#make raste from tempgrid
tempgrid = raster(extent(water.raster), crs = crs(as(rivers, "Spatial")), ncol = ncol(water.raster), nrow = nrow(water.raster))

#'make eles spatial
ele.spat = SpatialPointsDataFrame(ele2[,c("xutm","yutm")], data = ele2, proj4string = crs(ele.move))

#use a gstat model to interpolate temp across the landscape
library(gstat)

temp.interpolate = krige(temp~xutm+yutm, locations = ele.spat)

temp.interpolate = interpolate(object = tempgrid, model = temp.interpolate, filename = "temp.interpolate.tif", na.rm = T, ext = extent(tempgrid))

#'rasterise temperature
tempraster = rasterize(ele.spat, field = ele.spat@data[,"temp"], tempgrid, fun = mean)
#ncol(tempraster) = ncol(water.raster)
writeRaster(tempraster, filename = "tempraster500.tif", "GTiff", overwrite = T)

extent(tempraster) = extent(water.raster)
```

## load from file

```{r}
tempraster = raster("~/Documents/elephants/ele_data/temp_interpolate.tif")
crs(tempraster) = crs(water.raster)
```


# Get woody density raster

```{r}
treegrid = raster(SpatialGrid(grid.topo, proj4string = proj4string(as(rivers, "Spatial"))))

treeraster = rasterize(ele.spat, field = ele.spat@data[,"woody.density"], treegrid, fun = mean)

extent(treeraster) = extent(water.raster)
```

## get from file

```{r}
#run this code
#gdal_translate -projwin 321015.0 7347546.4 399130.9 7192628.0 -of GTiff /home/mtlab/Documents/rs-data/tree-cover.tiff /home/mtlab/Documents/elephants/ele_data/tree-cover-clip.tif

trees = raster("~/Documents/elephants/ele_data/tree-cover-clip.tif")
```

# Stack rasters

```{r}
extent(water.raster) = extent(tempraster) = extent(trees)
env = stack(water.raster, tempraster, trees)

save(env, file = "env-ssf.rdata")
```

